### ISSUE TITLE
OSM Import not georeferencing

### ISSUE THREAD

**Issue by dfgeorge** [OpenOrienteering/mapper#1007]
### Steps to reproduce
1. Import data from osm (attached file has a small sample, it is in UTM zone 54 S)
2. Check georeference data
3. Attached file has a map correctly georeferenced, produced while testing for issue 998

### Actual behaviour
Before applying fix for issue 998 importing data from OSM produced a geo-referenced map.
Now the import has no geo-reference data (UTM at 0,0)

### Expected behaviour
Map geo-referenced 

### Configuration
Mapper Version: 0.8.20171107 and 0.7.0
Operating System: windows 7 32 bit
[test2.zip](https://github.com/OpenOrienteering/mapper/files/1456918/test2.zip)

**Comment by dg0yt** [comment]
IIUC this happens when you import data using the new (GDAL/OGR) importer: You are not asked to configure the map's georeferencing (but you could do so in advance). This will need some more work. 

For now, the workaround is to add the data as a template first (which gives you the dialog you want), and then import this template. Unfortunately, it seems that no CRT file is suggested so you have to do this in another separate step...

**Comment by dfgeorge** [comment]
Thanks, the work around works great, didnt know it was possible to import templates.
