### ISSUE TITLE
Why the translations are locked for updates?

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#1033]
I'm ready to make a big contribution in to Map Symbols translation, but last few days all translations are locked. Please make clear the reason why the translation process could be locked. Thanks.

**Comment by dg0yt** [comment]
Translation are now unlocked again, at least until I finally commit changes which affect all Mapper translations (not map symbols). In order to fix #1030 (and this must be fixed before the next release) I will probably add a C++ namespace to all OpenOrienteering source code, and this changes the "context" of all translations.

I don't know what is the best place to document translations locks here: Open an issue, or add a note at the top of the translation page?
(I wish could leave a remark right in Weblate but it is not possible yet. I will have to create another feature request.)

**Comment by sikmir** [comment]
Any news? Namespace related changes are already done.

**Comment by dg0yt** [comment]
Unlocked.

Sorry, but it is not the same lock as 27 days ago. This issue was left open because I had asked a question:
> I don't know what is the best place to document translations locks here: Open an issue, or add a note at the top of the translation page?

**Comment by yevhenmazur** [comment]
Add a note at the top of the translation page - looks good, in my mind. The first place where I've looked when faced with locked translation was translations related article in wiki.
