### ISSUE TITLE
Cannot open manual

### ISSUE THREAD

**Issue by wanacode** [OpenOrienteering/mapper#1043]
### Steps to reproduce
1. From top menu Select Help > Open Manual
or 
1. Press F1 key

### Actual behaviour
In version 0.7.0 (Linuxmint and Debian) popup error message appears saying "Failed to locate the help files."

![screenshot at 2018-02-04 12-49-27](https://user-images.githubusercontent.com/2317149/35772830-ede89e98-09a9-11e8-9c52-fa3a75fb47a9.png)

In version 0.8.20180203 (linuxmint) simply nothing happens, i.e. no error message and no manual opens.

### Expected behaviour
I believe the manual should open in a window.

### Configuration
Mapper Version: 0.7.0
Operating System: Linuxmint 18.1 Serena (based on Ubuntu 16.04)

Mapper Version: 0.7.0
Operating System: Debian 8 Xfce 4.10

**Comment by Symbian9** [comment]
> In version 0.8.20180203 (linuxmint) simply nothing happens, i.e. no error message and no manual opens.

You should additionaly install additionaly `qttools5-dev-tools` (that include needed Qt5 Assistant).

> In version 0.7.0 (Linuxmint and Debian) popup error message appears saying "Failed to locate the help files."

That was known issue for v0.7.0 -- v0.7.91

- https://github.com/OpenOrienteering/mapper/issues/994

Now it fixed in v0.7.92 (bug fix release), so install it from here:

- https://software.opensuse.org/download.html?project=home%3Adg0yt&package=openorienteering-mapper-master

**Comment by dg0yt** [comment]
There is no hurry to switch from release to master, unless you want to test what will be release v0.8.0 in a few days.

You report duplicates #994 which has a title which fails to capture the symptoms, unfortunately. There are even update packages for v0.7.0, but they happened to get a lower build number due to the way branching/releasing works in the build system. So you probably missed the upgraded packge. I will try to make this work reliably with v0.8.

**Comment by wanacode** [comment]
This did come right with v0.8 but unfortunately I can not open the manual again in my current version.

**Configuration**
Mapper Version: 0.8.2
Operating System: Linux Mint 18.3 Sylvia (based on Ubuntu 16.04)

**Comment by wanacode** [comment]
I have also updated to version 0.8.3 now and still no manual opening unfortunately. Sorry, I don't understand from the replies here and #994 how I can fix this, or if it is possible to fix it on my end.

**Comment by dg0yt** [comment]
Please post the output of
~~~
dpkg-query -L openorienteering-mapper | grep Manual

**Comment by wanacode** [comment]
`
/usr/share/doc/openorienteering-mapper/Mapper 0.8.3 Manual.qch
/usr/share/doc/openorienteering-mapper/Mapper 0.8.3 Manual.qhc
`

**Comment by dg0yt** [comment]
So the help file are not zipped, which was the key issue in #994. 
The code checking for the help file's presence hasn't change since v0.8.0.
https://github.com/OpenOrienteering/mapper/blob/334bedf31b755ce7aeacdde7ffda9541d532189c/src/gui/util_gui.cpp#L133-L139

Running 
~~~
strace -e trace=file Mapper
~~~
might give an indication which files Mapper tries to lookup.

To start Qt Assistant manually, type:
~~~
assistant -collectionFile "/usr/share/doc/openorienteering-mapper/Mapper 0.8.3 Manual.qhc"
~~~
(Mapper does a little bit more than that.)

I can't say much more about Linux Mint, but on my Ubuntu 16.04, our v0.8.3, master, and unstable packages all open the *corresponding* help file without any problem.

**Comment by wanacode** [comment]
Thanks for checking this out further. I have resolved the issue and the manual now opens.

Running the `assistant` command showed an error relating to qt4. I installed the `qttools5-dev-tools` as suggested by Symbian9. My apologies I didn't try this sooner, I didn't fully understand initially.

Thanks for the help and the quick replies!

**Comment by dg0yt** [comment]
Thanks for feedback. Please open a new issue next time, and report the exact error message. I had to assume you were affected again by 
> ... opup error message ... saying "Failed to locate the help files."

We were dealing with the manual also in #541, and this is where we started to explicitly run the Qt5 version of Assistant.
