### ISSUE TITLE
Unable to open OOM 0.8.0 files in Purple Pen

### ISSUE THREAD

**Issue by IamShado** [OpenOrienteering/mapper#1058]
I am unable to open any map files saved in OOM 0.8.0 within Purple Pen (v 3.1.1).  
I get a file format error.

I can open the map file in OOM 0.7.0, save it then open in Purple Pen with no problems.

**Comment by dg0yt** [comment]
Purple Pen strictly refuses to open files with the new file format version number. This should be turned in a warning in Purple Pen IMO. But I don't know the plans of @petergolde.

**Comment by petergolde** [comment]
This has been fixed in version 3.1.2 of Purple Pen. It now correctly handles the new area clipping settings and the new option for disabling scaling of corner symbols on lines. As far as I can tell those are the only significant file format changes.

Thank you for tagging me so that I was aware of this release. It the future, please ping me when updating the OOM file format so that I can update Purple Pen also.

**Comment by dg0yt** [comment]
Thank you, Peter!

The next Mapper commit touching the file format is already prepared with a new file format documentation page and change log. Initially it will contain only new changelog entries, but that's a good start anyway.

In addition, you might be interested in testing the master builds which should be a fairly stable preview of what will become the next release.
