### ISSUE TITLE
Cannot open/read a saved .omap file

### ISSUE THREAD

**Issue by OakCastle** [OpenOrienteering/mapper#1061]
Anyone who knows why I can't open this .omap file I have been working on for many many hours today. I saved it regularly. After restarting OOM it seems to not like the file anymore. However, the file can be read/opened by Purple Pen. Can the file be rescued in some way?

Mapper Version: 0.8.0
Operating System: Win 10
[Ekensberg ISOM 2017.zip](https://github.com/OpenOrienteering/mapper/files/1765806/Ekensberg.ISOM.2017.zip)

**Comment by dg0yt** [comment]
At least the file seems to be complete, not truncated, when opened in a text editor. Strange that the error message is so useless.

**Comment by dg0yt** [comment]
Circumstances:
- The map has paper coordinates having an y component which is out-of-bounds for printing. This triggers a correction where coordinates are adjusted to come into the print area.
- All path objects store pattern anchor coordinates.
- One of the most recently used objects has an anchor with an y coordiante which gets out-of-bounds for storing in 32 bits. That's why an exception with a proper error message is raised. Enough to cause loading the file to fail.
- Mapper continues to try other importers which could handle the data. Our GDAL/OGR file importer can't tell that in advance, so it is tried even for this file. Of course it fails, and that's where the useless error message comes from.

Steps to do:
- [ ] Quick fix: Turn the out-of-bounds error into a warning for the pattern anchor coordinates.
- [ ] Investigate the source of the y coordinate issue. It should be possible to get into this situation unless mapping the whole world at once.

**Comment by dg0yt** [comment]
I triggered new master builds so you should be able to reopen the file again soon.

Only the last two objects generate warnings for out-of-bounds pattern origins. (The symbols of these objects are "301.1 NOK-ram tunn" and "403.0 NOK-gul", respectively.) Do you remember what did just before adding/editing these objects? Import, replace symbols, edit the georeferencing?

In total, the import drops 4 "irregular" objects, i.e. object having the start point or the end point far outside the printable area.

**Comment by OakCastle** [comment]
Hi,
Thanks for your help!

Yes I remember what I did regarding the two symbols.

1. As I originally began working with this file in OOM 0.7.X that did not
have a proper set of ISOM 2017 symbols. This was solved by downloading the
0.8.0 OOM version.
2. To change my symbol set from a beta version of a ISOM 2017 symbol set I
used earlier I simply started the new OOM version with the ISOM 2017 symbol
set.
3. As I did not know how to properly change symbols in the original file I
simply opened the old file as a background - followed by import and
discard. Now I had both the new and old symbols. So far so good.
4. This was followed by adding a couple of the laser background pictures I
used together with the original file (that wasn't impotsed together with
the map itself). So far so good.
5. Then I started a manual symbol swap, one by one followed by deletion of
the old ones. I had to keep two of the older ones though (elongated dot
knoll and boulder) as the new symbols were oriented 90° off axis compared
to the new ones. However, so far so good.
6. I believe the next step is the embryo of the problems that came later: I
opened a .ocd, or .omap, file that I knew containd our club logo. This logo
was marked and copied (ctrl+c) from the other file and pasted (ctrl+v) into
my new file. I noticed that the symbols in the NOK logo as well some
additional ones were imported to the symbol set. This was followed by some
changes of coulour to the three "NOK-xxx" symbols as well as tidying up of
the logo lines.
7. When I was finished I saved and exited OOM. As I tried to open the file,
just to be sure everything was ok, nothing happenend...

This describes more or less all the steps I did with the file/OOM. Yes the
file I nicked the NOK logo from was most probably geo-referenced. None of
the background files used were opened using geo-data.

Best regards,
Fredrik

2018-02-28 9:32 GMT+01:00 Kai Pastor <notifications@github.com>:

**Comment by mlerjen** [comment]
![image](https://user-images.githubusercontent.com/15611653/143827092-9fe75a2a-ee91-4de3-9e53-6f57bbf7e18d.png)
Is this related?
1) I have a non-georeferenced map in which I import an .ocd file. That works fine. I do some edits. Save and close.
2) On re-open I get the message, that it just dropped the imported map.
(3) On re-import of the same file it turns out, that the file is placed 670m left and 306m north of local map center).
(4) The imported map had it's own map center on the upper right corner of its map area, thus not far away.

**Comment by OakCastle** [comment]
I have no idea - everything works great except that you/I cannot export
pdf/vector files with OOM 0.9.5.

Fredrik

Den mån 29 nov. 2021 kl 08:47 skrev mlerjen ***@***.***>:
