### ISSUE TITLE
short 508 indistinct small path is continuous

### ISSUE THREAD

**Issue by hfm-zz** [OpenOrienteering/mapper#1094]
### Steps to reproduce
1.Select and draw 508 indistinct small path
2.Short path, should be 4 dashes long
3.

### Actual behaviour
draws a solid line, no breaks

### Expected behaviour
dashed line, 2 dashes, longer gap, 2 dashes

### Configuration
Mapper Version:0.8.1
Operating System:Win 10

**Comment by mlerjen** [comment]
Keep in mind that the minimum length of 507(!) Less distinct small footpath is 79.5m (ISOM 2017). This length is necessary to keep 507 distinguishable from 506 Small footpath. The symbol set in OOMapper just does not work below this minimum length, but is working above it.
![image](https://user-images.githubusercontent.com/15611653/39970939-c8d09e8e-56f3-11e8-9862-fba438df3c90.png)
![image](https://user-images.githubusercontent.com/15611653/39970924-b8f81640-56f3-11e8-908b-b818f19203e0.png)

**Comment by dg0yt** [comment]
The symbol set does work, but for dashed lines which are outside of the specification, it works in a different way than other software. You may call this "implementation-defined behaviour". 

On the positive side, this implementation makes it possible to draw small dashes manually instead of misguiding series of micro-dashes. The map maker has to make an explicit decision where she used to believe that the software would do the one right thing.

Importing and rendering existing OCD files is a different story.

**Comment by dg0yt** [comment]
Duplicates #251.
