### ISSUE TITLE
Text symbol duplicated when duplicating text

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#1130]
### Steps to reproduce
1. Open sample file 'forest sample.omap'
2. Save as OCAD version 12 file
3. Close map
4. Open the OCAD version 12 file
5. Copy 'Forest map sample' text via Ctrl+c
6. Paste 'Forest map sample' text via Ctrl+v

### Actual behaviour
The text is duplicated, but the text symbol (980.2) is duplicated as well!

### Expected behaviour
Only text should be copied, without adding a new symbol

### Configuration
Mapper Version: OpenOrienteering Mapper unstable 0.9.20180815
Operating System: Win7x64

**Comment by dg0yt** [comment]
In OCD version 8 format, I can reproduce this also in v0.8.2.

**Comment by dg0yt** [comment]
As I expected, this is a resulted of a 'unsafe' floating point comparison. 
*Line spacing*, character spacing and tab interval are stored as floating points in text symbol. Using the clipboard involves the OMAP format which has a different discretization that the OCD format, eventually leading to the decision to add another symbol.

For now I would fix the comparisons. In the long term, we might consider changing copy/paste to use just a key to cached binary map data, instead of holding XML data.
