### ISSUE TITLE
Bold text tags visible on warning window

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1140]
### Steps to reproduce
1. Set locale to "Ukrainian" ("українська")
2. Try open GIF as template

### Actual behaviour
Warning message include `<b></b>` tags.

![bold tag](http://i.imgur.com/PUS4hjS.png)
![bold tag 2](http://i.imgur.com/eZtWy9e.png)

### Expected behaviour
Check is it a bug or `<b></b>` should be removed from Ukrainian locale (and maybe other locales too)

### Configuration
Mapper Version: `0.8.x`, `0.9.x`
Operating System: *Debian 9*

**Comment by dg0yt** [comment]
This is only in the Ukrainian translation, since 2012. I guess it was you who introduced it (with best intentions) [1]. So please fix it yourself: https://hosted.weblate.org/translate/openorienteering/mapper/uk/?q=GIF

[1] https://github.com/OpenOrienteering/mapper/commit/c5d213c0b111ae9dd48b927629f10f899dce8f4f#diff-c16534cf492aac7150d23c194740d0f2L3675

**Comment by Symbian9** [comment]
> I guess it was you who introduced it

Yep...

Just fixed it on Weblate ;-)
