### ISSUE TITLE
Display problem with dark theme

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#1284]
I use dark theme for all Qt applications by setting the environment variable `QT_QPA_PLATFORMTHEME=qt5ct`, and it's a bit inconvenient having to run `Mapper --platformtheme xcb` to avoid display problems.

### Steps to reproduce
```sh
$ crudini --set ~/.config/qt5ct/qt5ct.conf Appearance custom_palette true
$ crudini --set ~/.config/qt5ct/qt5ct.conf Appearance color_scheme_path /usr/share/qt5ct/colors/darker.conf
$ Mapper --platformtheme qt5ct
```

### Actual behaviour
![scr2](https://user-images.githubusercontent.com/688044/60745094-6e33d900-9f81-11e9-8d5a-3d104fd12675.jpg)

### Expected behaviour
![scr1](https://user-images.githubusercontent.com/688044/60745105-755ae700-9f81-11e9-8774-695d260aae4b.jpg)

### RCA
https://github.com/OpenOrienteering/mapper/blob/2e6df59ca44e80f5faeba64dc7a0b6680d6d737a/src/main.cpp#L174-L176

### Configuration
Mapper Version: 20190622.5.r65.g0c126a7b
Qt Version: 5.13.0
Operating System: Archlinux

**Comment by dg0yt** [comment]
With the "darker" qt5ct palette, isn't the expected behaviour like this:

![Bildschirmfoto von 2019-07-06 06-46-53](https://user-images.githubusercontent.com/13567791/60751738-67c25300-9fbb-11e9-880a-8ca6c980a252.png)

**Comment by sikmir** [comment]
> With the "darker" qt5ct palette, isn't the expected behaviour like this:

Yes, but I thought OOM intentionally tries to ignore platformtheme for some reason. Otherwise dark theme is fine here.

**Comment by dg0yt** [comment]
> Yes, but I thought OOM intentionally tries to ignore platformtheme for some reason.

Mapper needs to use a proxy style, but setting the application's style resets the application's palette. The line you mentioned is where we try to set the right palette, again, but `QApplication::style()->standardPalette()` turns out to be not the right one (and obiously not working on macOS at some time). I always have trouble with the complex interplay of platform, theme and style in Qt. In some areas, there is little documentation and no public API.

For the dark screen shot, I set the palette to the one before calling `QApplication::setStyle()`. Maybe this is what is needed. In addition, according to the docs, some steps should be done before creating the QApplication object. And there seems a lot of [recent bugfixing activity in this part of Qt](https://code.qt.io/cgit/qt/qtbase.git/log/?qt=grep&q=palette). So this needs testing on a broad range of configurations (version x platform x theme x style, where version is only 5.12 for anything but Linux).
