### ISSUE TITLE
OCD import - misplaced georeferenced OCD templates

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1302]
### Steps to reproduce
1. Open OCAD file with vector (previous maps in .ocd) templates.

### Actual behaviour
Templates are places at map origin instead of being aligned with other templates. Closing the templates and reopening them ensures correct placement.

### Expected behaviour
Templates should appear at the right position on the first attempt.

### Root cause
The .ocd templates are listed in background map (type 8) parameter strings without any rotation or positioning:
```
...
 8 	oldmap_ANONYMIZED_ocd12.ocd	s0	r1
...
```
However, Mapper does fill in some defaults for position, scale and rotation instead of reading these values from the georeferenced map. Another point is that this is happening without any warning about missing parameters.

### Configuration
Mapper Version: current `dev`
Operating System: openSUSE Tumbleweed

**Comment by dg0yt** [comment]
How to proceed with this issue? I'm feeling unhappy with this bug being assigned, but without reproducible example or progress, for such a long time.

**Comment by lpechacek** [comment]
Understood. I've got some hack in a topic branch which I can share in case you want to take the issue over. I can also share a reproducer.

**Comment by dg0yt** [comment]
At least I would be willing to look into it. I'm already working on templates, OCD, and georeferencing.

**Comment by lpechacek** [comment]
https://github.com/OpenOrienteering/mapper/commit/291c0ef67de416285e03d6ae0e361d37bc8770b5 is my shot at the problem. I started with tracking uninitialized data but I didn't like the the development direction and haven't returned to the topic. As far as I remember, the idea was to prevent filling in "sane defaults" into places which weren't specified in the file.

I've sent data for bug replication via e-mail.

**Comment by dg0yt** [comment]
- We need to calculate the positioning in this case. That's what we already do when the user adds a new `MapTemplate` (not georefernced), but not when loading from OCD.
- We probably also want to save the OCD as before, i.e. with no explicit positioning instead of the calculated transformation. This should be easy if we remember that we have a georeferenced template.
  (Side note: Which one is the minimum version of OCD format which supports georeferenced templates?)

To get this resolved, we need to restore the support for `is_georefenced == true` in `TemplateMap` first. It is useful, and it shouldn't be too hard: I already do this in `GdalTemplate` which inherits from `TemplateMap`, and I know some cases which I shall test.

Will you find some time to look at GH-1645? I will probably add these commits on top of it.

**Comment by lpechacek** [comment]
> (Side note: Which one is the minimum version of OCD format which supports georeferenced templates?)

It looks like OCAD 9 was the first version that supported georeferencing, including georeferenced templates. As an anecdote, I also heard that there was a bug in OCAD preventing the use of differently scaled .ocd maps as a template. I've just checked that Mapper deals with differing map scales just fine.

**Comment by ollesmaps** [comment]
I justed checked and even the latest version of Ocad does not handle scales well. If Ocad is opened as a template and its scale differs, it does not display correctly.

**Comment by lpechacek** [comment]
So, this limitation is asking for a warning in the export path. Otherwise, we will keep receiving issue tickets about misplaced templates in OCAD. Sigh...
