### ISSUE TITLE
Using Terra Incognita with OOM

### ISSUE THREAD

**Issue by PeteSNelson** [OpenOrienteering/mapper#1401]
The problem:
Terra Incognita is a free app that that makes it easy to generate georeferenced aerial photographs.
It would be very good to use these images directly in OOM.
Terra Incognita can export as arcview, BSB.KAP, GpsDash,Garmin JNX, Opengis KMZ, OZIExplorer, SmartComGPS, TrekBuddy, UI View for PRS, TomTom. I've tried a few with OOM with no luck. I export as ARCVIEW to QGIS, then change the CRS to the reference system of my map and export from QGIS as georeferenced TIF or JPG.  If I could get OOM to accept this directly it would save a step.  
 
What happens:
When I load the ARCVIEW jpg to OOM I choose 'custom PROJ.4' and then start to enter the CRS.  The CRS does not have an EPSG code, so I try to enter the CRS I get from QGIS: "merc + lon_0=0 + k=1 + x_0=0 + y_0=0 + datum=wgs84 + units=m + no_defs".  I get an error "no colon in init= string"

Sample attached as a zip file.  Unable to load the files separately.
[Terra Incognita sample.zip](https://github.com/OpenOrienteering/mapper/files/3778228/Terra.Incognita.sample.zip)

### Configuration
Mapper Version: 0.9.0
Operating System: Windows 10

**Comment by Symbian9** [comment]
FTR, *TerraIncognita* app website:

- https://sourceforge.net/projects/terraincognita2/

**Comment by dg0yt** [comment]
Not sure if you really see
~~~
merc + lon_0=0 + k=1 + x_0=0 + y_0=0 + datum=wgs84 + units=m + no_defs
~~~
because the proper form would be
~~~
+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
~~~

---

Mapper should already accept any file which provides the data and which is common enough to be understood by GDAL. However:

- Mapper has native world file support (the `.jgw` file). But this format just carries a simple transformation, not the relevant coordinates reference system (CRS).
- The `.prj` file given here is not of a format I could identify. (GDAL knows `.prj` files which come with Shapefiles, and they contain CRS information in Well-Known-Text (WKT) format.)
- The `.aux.xml` has WKT embedded. It is common enough, and it is indeed examined, e.g. a CRS is found. However, GDAL doesn't find information how the image's pixel map to the CRS. That's a pity because... there is the world file which has that information.

---

It looks like we can combine these details in Mapper quite easily.
