### ISSUE TITLE
GPX export has lat/lon coordinates swapped

### ISSUE THREAD

**Issue by nalajcie** [OpenOrienteering/mapper#1433]
### Steps to reproduce
1. Create new map
2. Set up georefencing (I used EPSG 2180 as this was the Template map georeference)
3. Put one point object on the map
4. Use Export as -> Geospatial vector data and input file with GPX extension
5. Check the contents of created GPX file (the created waypoint coordinates)

### Actual behaviour
The created GPX file has the lat/lon attributes reversed. Editing the GPX file by hand and swapping the lat/lon values provides the correct waypoint placement.

### Expected behaviour
The created GPX file should have used the correct coordinates.

### Configuration
Mapper Version: 0.9.0
Operating System: Windows 10 64bit

I can provide some test files (eg. georeferenced file with georeferenced template (png + pgw) in EPSG 2180) if there is a need (not doing it right away as I have only very large templates on hand and reproducing the issue from new empty file was straightforward).

**Comment by dg0yt** [comment]
Thanks for reporting. This issue can be reproduced with the "complete map" example. Like all recent axis order bugs, this is related to the PROJ 6 / GDAL 3 transition. I'm somewhat surprised by this particular bug though, because we simply feed GDAL's GPX driver with well-referenced geo coordinates.
