### ISSUE TITLE
used symbols have "Always oriented to North" unset when imported from .ocd

### ISSUE THREAD

**Issue by shiroyagi** [OpenOrienteering/mapper#1492]
### Steps to reproduce
1. import a .ocd file
2. click on symbols such as 'x' and see that they are always oriented to North

### Actual behaviour
Those that are used in the map are no longer oriented to North, those that are not are.  This is a problem if the map is then rotated.

### Expected behaviour
This property should not be changed from the default during import, or there should be a warning and an option to reset them all back to the default.

### Configuration
Mapper Version: 0.9.1
Operating System: Linux

See comments on  #1235

**Comment by dg0yt** [comment]
Which version of OCD?

**Comment by shiroyagi** [comment]
Mapper does not appear to tell me the version.  I don't have access to OCAD and there are no obvious strings in the binary file.  It is from 1999 however.

**Comment by dg0yt** [comment]
We do handle the "not oriented to north" flag at least in some cases. I will need to know the cases that don't work.

**Comment by shiroyagi** [comment]
As far as I can tell, all used symbols. eg. 314.0 special water feature.  I notice that 314.1 is oriented to north but is not used.  Does there need to be a mechanism to migrate old symbols to new ones?

**Comment by dg0yt** [comment]
314 is a point symbol, and it works for me as expected.

I don't know what implementations of 314.0 or 314.1 you are refering to. Symbol sets from OCAD have particularities, and many map makers add more modifications. That's why I normally ask for test files and precise instructions how to reproduce issues. If desired, you can receive a private upload link via e-mail (see my profile for contact data).

BTW 1999 would mean OCAD 7 or earlier, cf. https://www.ocad.com/en/timeline/. You would probably get an error when trying to save an OCD 7 file without explicitly choosing another version or format.

**Comment by shiroyagi** [comment]
BOF symbol set, 314 is a blue 'x'

**Comment by dg0yt** [comment]
No symbol 314 in current OCD9 symbol sets from https://www.britishorienteering.org.uk/mapping_resources. 
No problem for 419 (green X), BOF OCD9 ISSprOM symbol set. 

If you want *your* issue to be solved, you may need to share *your* data, at least via a private channel.
