### ISSUE TITLE
Add install instruction for iOS Jailbreak

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#1509]
### Actual behaviour

While Apple won't let GPL software into the app store, and thus it would be effectively impossible to distribute the app, there is project on 'self rooting' iOS devices with Jailbreak.

So, those Jailbreak users could built & install *Mapper* on own iOS devices, BUT there are NO any info in `INSTALL.md` how Jailbreak's users could build *Mapper* yourself.

### Expected behaviour

Add *Mapper* install/compiling instruction for iOS Jailbreak users in `INSTALL.md` (or in Wiki).

### Configuration

- **Mapper Version:** `0.9.x`
- **Operating System:** iOS (Jailbreak)

**Comment by dg0yt** [comment]
From Facebook:
> Does it work in ios?

The correct answer is: No, there is no iOS version.

> Yes, its possible to build OpenOrienteering Mapper for iOS

At the moment, this is at least unknown, and due to particularities of mobile platforms, more likely to be outright wrong. A correct statement is: 
*It may be possible to build OpenOrienteering Mapper for iOS, with additional modifications.*

So for now, this request is invalid, because it is not just a matter of instructions. And I'm not going to indicate that iOS is a supported configuration.

**Comment by Symbian9** [comment]
>  There is no iOS version. It may be possible to build OpenOrienteering Mapper for iOS, with additional modifications.

OK. Thanks for the statement.

**Comment by Symbian9** [comment]
JFTR, There is a way to install 3rd-party apps on iOS without Jailbreak:

- https://github.com/rileytestut/AltStore
