### ISSUE TITLE
Counter-intuitive behavior of Move template function

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#1517]
A tiny annoyance.

### Steps to reproduce
1. Select a template in _Template setup window_
2. Activate _Move by hand_ button
3. Align chosen template
4. Select another template
5. Align the newly selected template

### Actual behaviour
The first selected template moves.

### Expected behaviour
The newly selected template should move. Alternatively, _Move by hand_ is deactivated on template selection change.

### Configuration
Mapper Version: v0.8.4
Operating System: openSUSE Tumbleweed

**Comment by mlerjen** [comment]
The same if using the "adjust" dialog. You have to close the window, select another template and re-open the window to get the focus on the second template.

**Comment by dg0yt** [comment]
To do:
- [ ] define to how send the template selection change from the template window to the tool:
  From the template list directly to the tool, or via the central MapEditorController, something else?
- [ ] define how to handle switching to a georeferenced template, or to the map.

**Comment by lpechacek** [comment]
>     * [ ]  define to how send the template selection change from the template window to the tool:
>       From the template list directly to the tool, or via the central MapEditorController, something else?

Currently, all the handling (button/action creation, tool instance creation, button enable and disable) happens in `TemplateListWidget`. I propose handling tool update/teardown on template selection change there too.

>     * [ ]  define how to handle switching to a georeferenced template, or to the map.

I think this question has been answered by commit 4622c8e7c6e68122402e29fb4f5ee0754da5e92c, specifically the `// Properly tear down positioning activities` part. 

>     * [ ]  define what to do if multiple templates get selected (e.g. for grouping).

For the record, multiple template selection and template grouping is not yet supported for end users.

Good question. In this case, my thinking is to check status of currently activated tools, deactivate them and then reactivate those which can be reactivated. In short, that would be equivalent to manual deactivation of all tools, selection of a new template, reactivation of all tools which can be reactivated. That would cover also all previous points.

Opinions?

**Comment by dg0yt** [comment]
> Opinions?

Fine for me.

I tried to review my concerns about where to handle selection. For the record, we already have:
- objection selection in `Map`
- symbol selection in `MapEditorController`

I don't want to say this is right or wrong, however the case of object selection seems questionable.

**Comment by mlerjen** [comment]
![image](https://user-images.githubusercontent.com/15611653/74011932-56925800-4989-11ea-801a-8186cedc8e1b.png)
fig.1. Adjust Template Window: No indication of the referred template.

As for the "adjust" variant I would like to propose:
1) Make clear to which template the adjustment refers to. e.g. in the windows titel bar. "Adjust Template TOM.jpg"
2) Dismiss the selection of another template in the template dialog as long as there is an open "adjust" window. Instead of accepting a new selection set focus back on the "adjust" window and pop up an alert "Quit template adjustment? ->Yes / No.

For the "move by hand" variant I would like to propose to plain drop the "move by hand" tool back to the "select tool" on changed template selection.
