### ISSUE TITLE
.gpx file doesn't import correctly if map in EPSG 27700

### ISSUE THREAD

**Issue by PeteSNelson** [OpenOrienteering/mapper#1570]
### Steps to reproduce
1. Create map in EPSG 27700
2. Import any .gpx file, or load as template
3. Check position - .gpx is about 80m to west
4. Change map to UTM
5. Import .gpx file.  Now in correct position

### Actual behaviour
I use maps in OSGB36 (EPSG 27700) - the crs for the UK national mapping agency.  If I use any .gpx file, it appears in the wrong place, whether as template or import.   

If I use a shapefile in UTM with the map in EPSG 27700, I get the same problem.  If the shapefile and the map are in same CRS (UTM or EPSG 27700), it is ok.

### Expected behaviour
.gpx files to appear in the right place on a map with crs set to EPSG 27700
Tell us what should happen instead

### Configuration
Mapper Version: 0.9.2
Operating System: Windows 10

**Comment by dg0yt** [comment]
UTM is not the only CRS is which is known to work. 
I guess there is an issue with doing the right transformation for EPSG 27700.
Now when I have to search for test data myself, it will take a little bit longer.

**Comment by dg0yt** [comment]
Hm, I can't see anything wrong comparing Mapper with [OSGB](https://www.ordnancesurvey.co.uk/gps/transformation/):

![EPSG27700](https://user-images.githubusercontent.com/13567791/78596044-63c5a900-784b-11ea-953a-585c7238f6d5.png)

**Comment by PeteSNelson** [comment]
I got different results when I tried to replicate the problem. See notes on map.  Can't upload as .omap.
![Lowther EPSG 27700 from omap](https://user-images.githubusercontent.com/57093406/78597163-e8f98f80-7844-11ea-86f4-0755a81cdae1.jpg)

**Comment by dg0yt** [comment]
You could upload a ZIP archive, or send a direct e-mail.
Anyway, we should not compare UTM and EPSG 27700, as we don't use a direct transformation yet: Please focus on latitude/longitude (WGS84) vs. EPSG27700.

**Comment by dg0yt** [comment]
https://gridreferencefinder.com/os.php?gr=NY0607111978|306071_s__c__s_511978|1&t=306071%20%2C%20511978&v=r

**Comment by dg0yt** [comment]
I added the coordinates from  [the link](https://gridreferencefinder.com/os.php?gr=NY0607111978|306071_s__c__s_511978|1&t=306071%20%2C%20511978&v=r) to the georeferencing unit test in GH-1571, and the test passes on all platforms.

**Comment by PeteSNelson** [comment]
I have made three simple maps.  Each is based on a georeferenced aerial photo from Terra Incognita.  One map is in EPSG 27700.  One map is in the CRS that came with the photo.  One map is in UTM.
I made a gpx from each map, and reimported it into the same map.  It always came in a different place. When I save the map and reopen it, things are in a different place again.  See zip file attached.
[OOM georef and gpx test.zip](https://github.com/OpenOrienteering/mapper/files/4444127/OOM.georef.and.gpx.test.zip)

**Comment by dg0yt** [comment]
I can reproduce the issues on the non-Linux platforms. This may indicate another issue with the PROJ library or data. We use a "modern" version with Windows, macOS and Android, and we had some issues before. I still need to narrow it down.

**Comment by dg0yt** [comment]
It turns out that the problem is not with PROJ, but with (our usage of) GDAL, the data formats library. We let GDAL do the coordinate transformations. I duplicated our GDAL usage pattern in the georefencing unit test, which now fails not only for EPSG 27700:

~~~
FAIL!  : GeoreferencingTest::testProjection(EPSG 2056 Bern) Compared values are not the same
   Actual   (QString::number(OGR_G_GetY(pt, 0), 'f')): "46.952406"
   Expected (QString::number(latitude, 'f'))         : "46.951083"
   Loc: [/Users/runner/runners/2.165.2/work/1/s/test/georeferencing_t.cpp(369)]
FAIL!  : GeoreferencingTest::testProjection(EPSG 2056 GH-1325) Compared values are not the same
   Actual   (QString::number(OGR_G_GetY(pt, 0), 'f')): "46.501264"
   Expected (QString::number(latitude, 'f'))         : "46.500000"
   Loc: [/Users/runner/runners/2.165.2/work/1/s/test/georeferencing_t.cpp(369)]
FAIL!  : GeoreferencingTest::testProjection(EPSG 27700 NY 06071 11978) Compared values are not the same
   Actual   (QString::number(OGR_G_GetY(pt, 0), 'f')): "54.494291"
   Expected (QString::number(latitude, 'f'))         : "54.494403"
   Loc: [/Users/runner/runners/2.165.2/work/1/s/test/georeferencing_t.cpp(369)]
FAIL!  : GeoreferencingTest::testProjection(EPSG 27700 Lake District) Compared values are not the same
   Actual   (QString::number(OGR_G_GetY(pt, 0), 'f')): "54.494255"
   Expected (QString::number(latitude, 'f'))         : "54.494367"
   Loc: [/Users/runner/runners/2.165.2/work/1/s/test/georeferencing_t.cpp(369)]
~~~

**Comment by dg0yt** [comment]
I'm about to resolve the issue in Mapper, but I opened an issue for GDAL because I don't understand all details at the moment: https://github.com/OSGeo/gdal/issues/2392

**Comment by dg0yt** [comment]
Thanks again for reporting the issue, and for providing the test files. It turned out that Mapper was using an obsolete option to GDAL because this was part of the official documentation, and that this obsolete option caused unexpected behaviour in PROJ. So now there is a fix in PROJ, an update was made to the GDAL tutorials, Mapper will no longer use this option, and our unit tests were improved.

I plan to release a new master snapshot tonight, so that you verify that it works for you.

**Comment by dg0yt** [comment]
https://github.com/OpenOrienteering/mapper/releases/tag/master-v20200411.3

**Comment by PeteSNelson** [comment]
Thank you. I'll  try it tonight or tomorrow. PeteOn 11 Apr 2020 17:27, Kai Pastor <notifications@github.com> wrote:
https://github.com/OpenOrienteering/mapper/releases/tag/master-v20200411.3
