### ISSUE TITLE
Border lines do not match area outlines at inner corners

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#1602]
### Steps to reproduce
1. create in Ocad building symbol with "sunken" border line. 
See [rect2.zip](https://github.com/OpenOrienteering/mapper/files/4574442/rect2.zip)
2. import to OOM
3. Rectangle is not right

Mapper Version: 0.9.2
Operating System: Win, Adroid

![rect3](https://user-images.githubusercontent.com/20535899/80963654-b6c15a80-8e0f-11ea-861c-ccd38f187d6c.jpg)

**Comment by lpechacek** [comment]
This one is scary. The outline symbol has zero width and no color assigned. Still, it renders as a 0.2 mm black line!

On a closer look, I can see that 521.2 (Large Building Outline) has no width assigned but it does have a border line. Manual setting of proper width and unchecking the border checkbox can be considered as a workaround in this case.

Aleš, would you be so kind as to share the original .ocd for easier debugging, please?

**Comment by dg0yt** [comment]
> On a closer look, I can see that 521.2 (Large Building Outline) has no width assigned but it does have a border line. Manual setting of proper width and unchecking the border checkbox can be considered as a workaround in this case.

That's one of the corner cases which isn't handle sufficiently at the moment_ A border line on an otherwise invisible line. I guess this was chosen in order to have the object path be the real boundary, making it easy to work with imported data, e.g. from OSM, or to switch from solid black to gray with outline.

- [ ] We need to fix the offsetting of the border line when the main line width is zero. 
     The current implementation uses the sign of the main line do indicate the side of the border. This doesn't work for zero-width main lines.
- [ ] The UI disables configuring borders for zero-size main lines. This is consistent with the current implementation - but it doesn't clear border configuration which is already present.

Once the issue is corrected, we should consider a similar border configuration for our symbol sets. This might need another tweak: taking care of inside and outside for closed paths. At the moment we only have left side and right side.

The corner

**Comment by dg0yt** [comment]
In particular, you see errors with "inner" corners.

**Comment by ollesmaps** [comment]
Thank you guys! 
Attached is the Ocad file: [building.zip](https://github.com/OpenOrienteering/mapper/files/4579595/building.zip)

And you are right this definition was chosen in order to have the object path be the real boundary, making it easy to work with imported data.  
Especially urban maps would benefit from this tweak.
