### ISSUE TITLE
File>Import removes (area=yes) or groups (bridge=*) under other_tags from imported OSM objects

### ISSUE THREAD

**Issue by reinisberzins** [OpenOrienteering/mapper#1635]
OSM-ISOM 2017-2.crt and other CRT files actually list: area=yes. But after import I can't see it in the Tag Editor panel anymore. E.g. an 501 highway=service AND area=yes doesn't convert to 501 Paved area, but to 503 Road instead.

I think that that all original tags should be kept intact in all imported objects. Otherwise I have to check different imported objects in the Tag Editor one by one to determine which tags are kept/removed/grouped. 

Grouping under "other_tags" also complicates import and conversion of OpenStreetMap files. E.g. tunnel=* is kept intact, while bridge=* is grouped under "other_tags", but CRT understands only positive approximate references: other_tags~=bridge, but not negative: other_tags!~=bridge.

**Comment by dg0yt** [comment]
Not importing all OSM fields is a GDAL default:
https://gdal.org/drivers/vector/osm.html 
We do some customizing by providing and using [`mapper-osmconf.ini`](https://github.com/OpenOrienteering/mapper/blob/master/src/gdal/mapper-osmconf.ini). We may add more fields to be imported explicitly if desired. Or you can create your own copy, and set its path in Settings > GDAL/OGR > Configuration > `OSM_CONFIG_FILE`.

What looks like a bug is the fact that `area` is listed both in `attributes` and `ignored` in some sections of the file. This might explain why this attribute is lost in some cases.

In addition, I just extended the object query language to also have a NOT operator, cf. 
https://github.com/OpenOrienteering/mapper/pull/1631 
https://github.com/OpenOrienteering/mapper-manual/blob/object-query-v0.9.4/pages/find_objects.md

**Comment by reinisberzins** [comment]
Thanks! I edited my mapper-osmconf.ini according to your example:
Added attributes=bridge - it worked, now bridge tags import as separate fields (not grouped under other_tags).
Deleted ignore=area - it didn't work, "area" doesn't appear in the Tag Editor, and k="area" can't be found anywhere in my resulting .omap file. Currently my workaround is replacing replacing "area" with "yes_area" in my source .osm file, because this tag is not removed during import.

**Comment by dg0yt** [comment]
Thanks for the feedback. I will try to find out where the area tag gets lost.

**Comment by dg0yt** [comment]
GDAL doesn't preserve the `area` tag as a regular attribute:
https://github.com/OSGeo/gdal/blob/1c7fef4227e294ffd159e48d2dcb51ae0f6552f1/gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp#L2084-L2085

Reported as https://github.com/OSGeo/gdal/issues/2603.

**Comment by dg0yt** [comment]
Apart from solving the GDAL `area` issue, we might also do the following:
- Generally create a tag representing the layer in GDAL (where area=yes moves ways to "multipolygons" instead of "lines".
  (This needs code in Mapper. This may be useful also in other GDAL contexts, but in can interfere with tags named like our layer tag.)
- For OSM, let GDAL calculate another tag to indicate the is-area property. For example, we may add the following to the `multipolygons` section to mark the OSM ways which were turned to multipolygons due to an original area=yes tag.
   ~~~
   computed_attributes=is_area
   is_area_type=String
   is_area_sql="SELECT (CASE WHEN [osm_way_id] IS NOT NULL THEN 'yes' ELSE NULL END)"
   ~~~
  @reinisberzins This can be tested already now, by customizing the mapper_osmconf.ini and the CRT files.

Given that the GDAL patch won't reach Linux distributions, I'm inclined to use the calculated tag immediately.
