### ISSUE TITLE
mapper does not display menus on fedora32 wayland

### ISSUE THREAD

**Issue by westendred** [OpenOrienteering/mapper#1678]
### Steps to reproduce
1.Download latest release from GIT
2.compile
3.run mapper
4. menus do not display when clicked with the mouse

### Actual behaviour
menus do not display when clicked with the mouse

### Expected behaviour
Menus should display

When I switch to X window manager, menus display properly

### Configuration
Mapper Version:0.9.4
Operating System:fedora 32, wayland window manager

**Comment by dg0yt** [comment]
What about other Qt programs on wayland? E.g. `assistant` or `linguist`.

**Comment by westendred** [comment]
I switched back to wayland and mapper is displaying correctly now! Not sure why it wasn't working before, but probably something in my setup. I couldn't find packages for assistant or linguist, but VLC was displaying correctly as well which I believe uses Qt.

Thanks, Jim

**Comment by lpechacek** [comment]
Please note that even if you start Wayland, there is likely the `Xwayland` adapter running in the background. Mapper is then using the X protocol to communicate with the display instead of Wayland protocol. To start Mapper in "Wayland mode" you've got to add `-platform wayland` on the Mapper command line. As dg0yt suggested, it also makes sense to test other Qt based applications in the same environment to isolate the defect.

Anyway, given that issue has receded, I'm closing the ticket for the moment.
