### ISSUE TITLE
GeoTIFF files created in EPSG 27700 load incorrectly

### ISSUE THREAD

**Issue by PeteSNelson** [OpenOrienteering/mapper#1755]
### Steps to reproduce
1. Open files 'OOM base UTM.omap' and 'OOM base OSGB.omap'
2. Open as template files 'TIF from QGIS OSGB.tif' and 'TIF from OCAD OSGB.tif' 

Note: There are many more files available in other formats not included in the .zip. See the two pdfs for more info

### Actual behaviour
TIF files made in OSGB 1936 (British National Grid, EPSG 27700) appear 92 metres east and 14 metres south of correct position.
Except that 'TIF from OCAD OSGB.tif' and loaded in OOM UTM is correct.

TIF files made in UTM, and GPX, BMP, GIF, JPG files made in either UTM or OSGB (EPSG 27700) are all ok

See pdfs for more detail.

### Expected behaviour
TIF files should appear in correct postion.  The 2 x 2 km square on the template should match the square on 
[OOM georef files test.zip](https://github.com/OpenOrienteering/mapper/files/5409447/OOM.georef.files.test.zip)
the OOM file

### Configuration
Mapper Version: 0.9.4
Operating System: Windows 10

**Comment by dg0yt** [comment]
Thank you very much for this report and its preparation.

In a quick test, this also happened in v0.9.3.

Based on a first debugging session, there is an issue with using the CRS from the GeoTIFF. 
- Mapper initially gets `LOCAL_CS["OSGB 1936 / British National Grid",AUTHORITY["EPSG","27700"]]` from GDAL.
- Mapper lets GDAL create a spatial reference object from this string.
- Mapper lets GDAL export this object to PROJ4 syntax, which results in an empty string and error code 6. 
  Now the CRS information from the TIFF is already lost.

What we probaly need to do instead is to export to WKT instead of (legacy) PROJ4.

Anyway, for the existing templates uses the CRS stored for each template in the map file, here: 
`+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +units=m +no_defs`

---

Workaround for new templates: Don't use the CRS from the template file.

There seems to be another issue with suppressing the invalid CRS from the GeoTIFF.
In v0.9.4, the "From template file" option is active despite not having it, due to the first bug. But not in my debug build...

**Comment by dg0yt** [comment]
Works on Ubuntu 18.04 (PROJ 4.9.3, GDAL 2.2.3).

**Comment by dg0yt** [comment]
> Works on Ubuntu 18.04 (PROJ 4.9.3, GDAL 2.2.3).

Here, I get different data. GDAL string from GeoTIFF: 
`PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["OSGB_1936",SPHEROID["Airy 1830",6377563.396,299.3249646,AUTHORITY["EPSG","7001"]],TOWGS84[446.448,-125.157,542.06,0.15,0.247,0.842,-20.489],AUTHORITY["EPSG","6277"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4277"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","27700"]]` 
PROJ4 string from GDAL: 
`+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs`

(The TOWGS84/+towgs84 stuff is not to be used with the current versions of PROJ/GDAL).

**Comment by dg0yt** [comment]
`gdalinfo` 3.1.1 seems to get better information than Mapper:
~~~
PROJCRS["OSGB 1936 / British National Grid",
    BASEGEOGCRS["OSGB 1936",
        DATUM["OSGB 1936",
            ELLIPSOID["Airy 1830",6377563.396,299.3249646,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4277]],
    CONVERSION["British National Grid",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-2,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996012717,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",400000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",-100000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["UK - Britain and UKCS 49°45'N to 61°N, 9°W to 2°E"],
        BBOX[49.75,-9,61.01,2.01]],
    ID["EPSG",27700]]
~~~

**Comment by PeteSNelson** [comment]
Thanks for responding so quickly.  Improvements made in 0.9.3 and 0.9.4 have already made it much eeasier to transfer from OCAD to OOM.
Why do TIF files made in mapper load correctly, but those made in OCAD11, QGIS or (old) Global Mapper do not?

**Comment by dg0yt** [comment]
> Why do TIF files made in mapper load correctly, but those made in OCAD11, QGIS or (old) Global Mapper do not?

Mapper does not create GeoTIFF at the moment. Perhaps it should ;-)

**Comment by PeteSNelson** [comment]
Thanks.  Lookng forward to trying it.

**Comment by dg0yt** [comment]
The issue is fixed for new templates.

There is still one sub-issue: The map file still carries the wrong CRS for each of the existing templates, and it will be used as if it was a user-defined custom CRS. They will not just automatically move to their right position. You have to take action, e.g. turn georeferencing off and on again for each of the templates.

I don't think we can check and warn everytime a map is loaded. At best, we could offer an explicit check action, e.g. in the Templates menu.

**Comment by dg0yt** [comment]
Now you can test: https://github.com/OpenOrienteering/mapper/releases/tag/master-v20201026.1

**Comment by PeteSNelson** [comment]
Tested OK in UTM and EPSG with 27 different templates as before.  
BMP, GIF, JPG, OCD, TIF, GPX in UTM and EPSG 27700, made in OCD, OOM, Global Mapper, and QGIS.   Almost all were within 2m.  
Some files made in UTM from QGIS (TIF, BMP, and JPG) were about 6m misplaced, both in OOM UTM and in OOM EPSG 27700.  QGIS files made in EPSG 27700 were ok.
This is very good.  Thank you.

**Comment by dg0yt** [comment]
Thanks. For maximum precision of some transformations, you may need an additional grid shift file from https://cdn.proj.org/, to be placed  in the `proj` folder:

[uk_os_OSTN15_NTv2_OSGBtoETRS.tif](https://cdn.proj.org/uk_os_OSTN15_NTv2_OSGBtoETRS.tif) - United Kingdom - OSGB 1936 (EPSG:4277) to ETRS89 (EPSG:4258). Size: 2.9 MB. Last modified: 2020-01-24

(However, we still need to find a way to offer similar on Android.)
