### ISSUE TITLE
Enhancement: Export as geospatial vector data: List all possible formats in dropdown menu

### ISSUE THREAD

**Issue by mlerjen** [OpenOrienteering/mapper#1778]
### Steps to reproduce
1. Mapper > File > Export as ... > Geospatial vector data
2. Dialog opens to define the file name and folder

### Actual behaviour
3. At the file format drop down menu there is a single entry "Geospatial vector data". The user must thus choose the export format by entering the corresponding file extension taken from the Mapper GDAL manual page.

### Expected behaviour
new 3. All possible export formats should be listed in the drop-down menu. According extension should be appended resp. changed to the file name according to the users choice.

### Configuration
Mapper Version: 0.9.4.
Operating System: Windows 7

**Comment by dg0yt** [comment]
Do we need to translate the formats?
(Looking at Cyrillic, Chinese etc.)
![formats](https://user-images.githubusercontent.com/13567791/99190686-515c0800-2768-11eb-85e8-72544b52c89e.png)

**Comment by yevhenmazur** [comment]
I'd like to translate only one string - 'Comma Separated Value'. Generally speaking the translation is not needed...

**Comment by jmacura** [comment]
> 
> 
> Do we need to translate the formats?
> (Looking at Cyrillic, Chinese etc.)
> ![formats](https://user-images.githubusercontent.com/13567791/99190686-515c0800-2768-11eb-85e8-72544b52c89e.png)

There are some occurrences of "format" or "spreadsheet" which could be translated, but for latin script languages this is not critical. I can't speak for the non-latin scripts though.

**Comment by dg0yt** [comment]
The strings come from GDAL itself and are as listed as Vector export drivers on https://www.openorienteering.org/mapper-manual/pages/gdal.html and of course on https://gdal.org/drivers/vector/. For best usage of each format, it is useful to consult the driver documentation for its configuration options.

Translation is all or nothing. Currently nothing. All means: complete strings (but without the extensions), all of them. Of course translators can choose to accept the source unmodified. I assume some translators might not be familiar with the formats, and this may lead to partial translations of strings which are less clear to those more familiar with relevant English keywords and identifiers.

**Comment by mlerjen** [comment]
I have to ask, what exactly will happen, if I choose e.g. the LIBKML format. As two formats are actually linked to this entry (.kmz, .kml), which one will be the chosen one resp. which file extension will be added? If I wanted to switch to the other option, I would have to do this manually, I assume ??

**Comment by dg0yt** [comment]
Some of the behaviours depend on the GDAL drivers. Test and report, so we can extend the documentation. And look into the relevant GDAL driver documentation first. On Windows/macOS/Android, you will face another KML driver, https://gdal.org/drivers/vector/kml.html, which has `.kml` only. Our online manual reflects these platforms.

> what exactly will happen, if I choose e.g. the LIBKML format. As two formats are actually linked to this entry (.kmz, .kml), which one will be the chosen one resp. which file extension will be added? 

I assume that a provided file extension will be respected by GDAL. 
If you don't provide a known extension, Mapper will automatically append the first one from the list.
If the GDAL driver does not provide extensions (e.g. GeoRSS), it will no longer be on the list.

> If I wanted to switch to the other option, I would have to do this manually, I assume ??

In some way, yes, always. No magic mind-reading ;-)

---

Our GDAL export feature is in the range of "low-hanging fruits". Some formats may need more code, in order to provide options to the GDAL driver. We don't have this yet.
