### ISSUE TITLE
Maybe? sec problem with DT_RUNPATH

### ISSUE THREAD

**Issue by pkturner** [OpenOrienteering/mapper#1852]
### Steps to reproduce
1. Build and install Mapper on Gentoo Linux, or
2. Install prebuilt binary package for Ubuntu.

### Actual behaviour
A warning occurs during installation:

    scanelf: rpath_security_checks(): Maybe? sec problem with DT_RUNPATH='lib/openorienteering-mapper-0.9.4/lib' in /var/tmp/portage/sci-geosciences/openorienteering-mapper-0.9.4/image/usr/bin/Mapper

I checked this by scanning the installed Mapper. Evidently, the security scan flags relative paths as a possible problem.

    $ scanelf --rpath /usr/bin/Mapper
     TYPE   RPATH FILE 
    ET_DYN lib/openorienteering-mapper-0.9.4/lib /usr/bin/Mapper 

I also downloaded the `openorienteering-mapper_0.9.4-0+32.2_amd64.deb` binary package, prebuilt for Ubuntu 20.4, to check whether the RPATH is relative in a prebuilt package. It is essentially the same as when built on Gentoo.

    $ scanelf --rpath usr/bin/Mapper
     TYPE   RPATH FILE 
    ET_DYN lib/openorienteering-mapper/lib usr/bin/Mapper

I'm not familiar enough with this to say that it represents an actual security problem. Googling for `rpath_security_checks`, it looks as if this check is unique to Gentoo.

### Expected behaviour
No warning. `DT_RUNPATH` is an absolute path.

### Configuration
Mapper Version: 0.9.4
Operating System: Gentoo Linux

### Related Code
The executable's DT_RUNPATH is determined by the setting of CMAKE_INSTALL_RPATH.

**Comment by dg0yt** [comment]
Thanks for reporting. I think we really need to review this setting. However, DT_RUNPATH is not exactly the same as DT_RPATH, and maybe we didn't want to set it:
https://en.wikipedia.org/wiki/Rpath

This what CMake is saying about RPATH:
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling 

We touch `CMAKE_INSTALL_RPATH` in `src/CMakeLists.txt`.

What do we need RPATH for?
- Android and Windows don't use RPATH anyway.
- For macOS, it needs to point into our installed bundle because we carry third-party libraries as shared objects. And another mechanism needs to point to the shared objects when running tests which are not installed.
  But we don't touch RPATH for macOS.
- For Linux, it used to need to point in a dedicated lib path when we carried third-party libraries as shared objects. But it is not needed at the moment.

I will try to remove our `CMAKE_INSTALL_RPATH` setting entirely.
