### ISSUE TITLE
Editing in progress set to true when not editing

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#296]
**Somebody reported on Sourceforge [[tickets:#296](https://sourceforge.net/p/oorienteering/tickets/296)]:**

There is a way to do this somehow! I was helping someone new use Mapper, and we got into this bad state and weren't sure how to get out of it. FWIW Drawing a circle cleared the issue. No repro at the moment.

**Comment by dominikzalewski** [comment]
I had the same issue twice or three times. Mostly on tablet while field-working. Due to misleading for me (at that time) message from auto-recovery (I had to kill the app to exit), lost 30 minutes of fieldwork a few times. I was pretty annoyed. Also don't know exactly what's the path to reproduce it.

**Comment by dg0yt** [comment]
Some of the situations have been fixed since 2014. Please report the version of Mapper when there are new occurences of this issue.

**Comment by dominikzalewski** [comment]
It was 0.5.3 or something older, but certainly not 0.6. I had occurrences of this issue in May/June 2015 running the latest version on Android that was available at that time. I did a bunch of mapping in December 2015 on the new version 0.6 and never came across this issue.

It's really hard to reproduce and I also never figured out how to reproduce it. I remember I was trying to experiment with how much can be done on a tablet trying to cut holes in areas on Android, when it happened to me the first time. That's all the 'context' I remember.

Since there is no clear reproducing scenario, I'm not inclining to keep this issue open.

**Comment by dg0yt** [comment]
All right, thanks for explaining. The issue is left open because it was a confirmed bug with unclear triggers. I need to collect enough evidence that the bug is fixed before I close this issue.

**Comment by dg0yt** [comment]
I guess this is fixed. New reports will have to describe what was done just before such a situation.
