### ISSUE TITLE
Select objects using tags

### ISSUE THREAD

**Issue by dg0yt** [OpenOrienteering/mapper#358]
**gandym01 reported on Sourceforge [[tickets:#358](https://sourceforge.net/p/oorienteering/tickets/358)]:**

In future, can a tool be provided to select objects on the basis of an imported tag(s)? For example, I imported a DXF file and found, via the tag editor, that the layer number was provided as a key-value pair (key:name, value:30). The ability to select all objects with a certain key-value pair(s) would make applying symbols to newly imported DXF data (that contains many different layers) much easier and give an effective workaround to [Ticket 288](https://sourceforge.net/p/oorienteering/tickets/288/).

Also, does this mean [Ticket 337](https://sourceforge.net/p/oorienteering/tickets/337/) might already be partially achieved?

gandym

**Comment by mitchellkrome** [comment]
I have made a small widget that allows for selecting objects based on the tags. Open to any comments on the layout, otherwise can make a pull request with the code.

![tag_selector](https://cloud.githubusercontent.com/assets/8371236/20820320/32ca76ba-b886-11e6-944d-d7d41c5942c9.PNG)

**Comment by dg0yt** [comment]
Basically looks good to me.
 - Instead of comparison "not", I would prefer "is not".
 - Is there any precedence of relation "or"/"and"?
 - Would it make sense for relation be the first column (empty/disabled for the first row)?
 - Is this the right thing for a dock widget, or should it be a dialog instead?

(I would have implemented a pure text search with keywords, but your approach is fine as well.)

**Comment by mitchellkrome** [comment]
- Is there any precedence of relation "or"/"and"?

Precedence was something I had a bit of trouble working out how to do well with this sort of layout- the way I've written it now it evaluates top down with "and" and "or" having the same precedence.

- Would it make sense for relation be the first column (empty/disabled for the first row)?

First column makes more sense - I'll give it a go.

- Is this the right thing for a dock widget, or should it be a dialog instead?

Almost everything I've seen in mapper so far used these dockable type things so I just went with that because it gave me something to base the code off which already used a table, etc (This is the first time I've messed around with Qt). QGIS has a similar "select by value" feature which is a dialog and I find that it always gets in my way when I try to use it. With a dialog do you imagine some sort of one use popup that goes away when you make the selection, or just the same thing but it can't be docked into the interface?

I thought about a text type thing but felt that it wasn't very user friendly - in QGIS there is "select by feature" which lets you write an expression but I find that it's usually too complicated for what I want to do. Maybe in the future having some sort of basic expression language to write more complicated queries on the objects would be useful though. It would make precedence much easier.

**Comment by dg0yt** [comment]
We can deal with precedence in documenation. This the main reason why I ask. The explicit approach would be to add columns for parentheses. This increases complexity a lot.

I have no strong opinion on make this a dialog. It is just that I consider this to be very much like a search dialog: Only immediately after clickling "Select", there is a strong correlation between input and selection.
(In the end it is just a widget, and we can quite easily move it from a dock widget to a dialog.)

**Comment by marcovandersson** [comment]
I would very much appreciate such SQL thing for selecting tag names. That should easily solve the enhancement reported in #807. Go for it! Implement it right now :-)

**Comment by dg0yt** [comment]
This is now implemented by action "Tag selection" from the View menu (Ctrl+Shift+5). Many thanks to new contributor @mitchellkrome.

Operator 'and' has precedence over operator 'or', i.e. queries are interpreted as:
(a AND b) OR (c AND d AND f) OR x.

Updated unstable builds will appear later today.
