### ISSUE TITLE
Map coordinates too high

### ISSUE THREAD

**Issue by zmalinowski1968** [OpenOrienteering/mapper#513]
When a map is georeferenced by adding a Open Street Map template and high scale is choosen (ex. 1:4000 or even higher) and UTM is used, Y map coordinated became very high. In my example it was about 1,500,000 milimeters. This is not an issue by itself but Export ad Print screens do no allow coordinates higher than 999,999.99.

I did fount the solution by typing Reference Point coordinates but I did it by experience and moreover - this is something I could only when attaching first georeferenced template, it is not possible to "move" map coordinates afterwards.

This is slightly complicated, I thing you should be able to move map coordinates later on.

**Comment by dg0yt** [comment]
Okay, this is a issue when georeferencing a map while loading some geodata. I try to deal with this soon. baronmax reported a similar issue in a comment to #432.

Because I reduced the internal coordinates precision from 60 [!] to 32 bits, a similar correction has to be made when a map is loaded. The idea is to check the first map coordinate. If it is outside a certain distance from the origin, it will be used as the offset to move all coordinates to the origin.

**Comment by dg0yt** [comment]
Steps to reproduce:
1. Create a new map, 1:4000
2. Click Templates > Open Template... and select a .osm file, e.g. from Mainz, Germany
3. In the "Opening track..." dialog, select "Georefenced".
4. In the "Map Georeferencing" dialog, change nothing but select "UTM" coordinate reference system.
Now the template is positioned out of the acceptable range of the print dialog.

The trouble starts (and can be worked around) in step 4. Initially, the geographic reference point is set properly from the track data. However, the option "On CRS changes, keep:" has neither "Projected coordinates" nor "Geographic coordinates" selected. When the user selects "UTM", the geographic coordinates get updated from the projected coordinates which are "0 0" at that moment... That's why the template is not positioned at the coordinates origin.

The solution (and workaround) is simple: First set "On CRS changes, keep:" "Geographic coordinates", than select "UTM". Now the geographic reference point remains unchanged, and the corresponding UTM coordinates are placed at the map origin.

TODO:
- Fix the dialog in step 4.
- Provide an action for moving the map.
- Do a check and provide the move action when opening the print dialog.
