### ISSUE TITLE
Manual will not open in Linux

### ISSUE THREAD

**Issue by wanacode** [OpenOrienteering/mapper#541]
I cannot open the manual in the software, either from the menu or with the shortcut key F1.

For now I am using the online version http://sourceforge.net/p/oorienteering/wiki/Manual%20Contents/

This is a problem on Linux Mint 17.1 with version 0.5.96 and also on Debian Jessie Xfce version 0.5.99

**Comment by dg0yt** [comment]
Is there an error message, and what does it say?

**Comment by wanacode** [comment]
No, just nothing happens. No error messages.

**Comment by dg0yt** [comment]
This is strange. There should be an error message if either the manual or Qt Assistant would be missing. (The manual works in Windows and Ubuntu 14.04 packages.)

**Comment by dg0yt** [comment]
This behavior is caused by qtchooser. Run "assistant" on the command line to see what happens. It even exits with an error. But Mapper doesn't wait for the exit code: it only verifies that the program could be started.

Solution: Set QT_SELECT environment variable to "qt5".

References:
- http://perezmeyer.blogspot.com.ar/2013/08/qt-in-debian-using-qt4-andor-qt5-in.html

**Comment by dg0yt** [comment]
The common solution for Ubuntu, Debian, LFS, Arch is to set the QT_SELECT environment variable to "5", not "qt5".
