### ISSUE TITLE
Drawing angles works differently

### ISSUE THREAD

**Issue by dl3sdo** [OpenOrienteering/mapper#549]
When drawing lines (not curves) the behaviour when pressing Ctrl depends whether the point is an endpoint or an intermediate point:
For an endpoint only 90° angles (i.e. 4 directions) are offered whereas for intermediate points the angles depend on existing angles (i.e. 12 directions) and they are not equally distributed, see attached screenshot.
![drawingangles1](https://cloud.githubusercontent.com/assets/14225666/11614108/3e84ac5c-9c38-11e5-8241-dc2866f87df2.png)

**Comment by dg0yt** [comment]
For an inner point, there are two incoming edges. In addition to a pair of pendicular lines for each edge, another perpendicular pair consists of the angle bisector and the tangent.

For an end point, with only one incoming edge, this idea folds down to a single pair of perpendicular lines.

So what is the problem here?

**Comment by dl3sdo** [comment]
I see no problem, the behaviour was for me just not clear.
