### ISSUE TITLE
xmap/omap files currently refers to a non-existing XML Namespace URI

### ISSUE THREAD

**Issue by Abbe98** [OpenOrienteering/mapper#554]
Currently all XMAP/OMAP files refers to `http://oorienteering.sourceforge.net/mapper/xml/v2` witch returns an 404 error.

What about moving the development of the XMAP/OMAP format into a separate repo and provide the file from there? That repo would also be a great place to provide and maintain the spec documentation.

**Comment by dg0yt** [comment]
The XML namespace attribute is just an ID, not (neccessarily) a real resource. Cf. https://en.wikipedia.org/wiki/XML_namespace. In that sense, it isn't broken. 

The spec documentation doesn't suffer from a missing place but from missing attention...

**Comment by Abbe98** [comment]
I guess a resource(such as a XML template) is expected when the URI starts with referring to the HTTP protocol?

**Comment by dg0yt** [comment]
No, I don't think so. I don't want to look it up in the XML spec now, but the Wikipedia article puts it in these words: "Using a URI (such as "http://www.w3.org/1999/xhtml") to identify a namespace, rather than a simple string (such as "xhtml"), reduces the probability of different namespaces using duplicate identifiers. ... In general, however, users should assume that the namespace URI is simply a name, not the address of a document on the Web."

**Comment by Abbe98** [comment]
Closing this for now.
