### ISSUE TITLE
symbol_set_t test should not modify source file

### ISSUE THREAD

**Issue by gaudenz** [OpenOrienteering/mapper#580]
Running the symbol_set_t test rewrites the example maps. The file contents are the same afterwards, but the modification time changes. This confuses cmake which thinks it needs to rebuild the build system.

IMO running tests should not rewrite any source files. The test should instead operate on a temporary copy.

**Comment by dg0yt** [comment]
I admit ```symbol_set_t``` is not a typical test (i.e. as documented, it is to modify source files). But indeed it doesn't need to touch the sourcefiles if there is no change, and I will look into changing this for a future release.

However, the tests are meant to serve the developers, catching unintented (and intented) effects of changes. They were not invented with packaging in mind. Running ```symbol_set_t``` as a test during development helps to catch unintented changes in file format.

Note that normally it is not a problem to rerun CMake. IMHO you observe a problem because during the CMake rerun, the environment is to different from the initial run - clipper cannot be found via pkgconfig.
