### ISSUE TITLE
Consider moving translations to Web

### ISSUE THREAD

**Issue by Abbe98** [OpenOrienteering/mapper#605]
Maintaining translations could be easier for new through Transifex, no need to understand things such as Git or XML, also no need to install any software.

Translations could then be pulled from Transifex as a part of the build process.

Yep another service but I really think this project could benefit from this one.

**Comment by dg0yt** [comment]
Or https://weblate.org/?

**Comment by Abbe98** [comment]
Not personally familiar with Web late. Many relevant projects such as iD
and QGIS uses Transifex so people might prefer it.

**Comment by dominikzalewski** [comment]
Purple Pen uses ubuntu launchpad

https://translations.launchpad.net/purple-pen

I recently translated Purple Pen using this interface to Polish and otherwise I wouldn't. It's so convenient to do it this way. And the big plus of this is that I only translated 10 or 20 sentences each day. If I had to do it through repositories, or committing git, I would probably mentally try to find a slot of 1h or longer to do it. On launchpad you can even do it on a tablet while trying to put your baby to sleep. So if you ask me, I'd opt for ubuntu launchpad.

The other nice feature of ubuntu launchpad is that it already suggests translations from other projects. So for instance you don't have to type in what's the translation for 'File' or 'Window'. You just click a radio button on a suggested translation.

**Comment by dg0yt** [comment]
- I dislike the fact that Transifex is located at the Caymen Islands.
- Launchpad was under consideration when moving away from Sourceforge. It is more than just translation, which might cause some confusion.

Given that we provide Qt Translator and that [Github now allows direct uploads to repositories](https://github.com/blog/2105-upload-files-to-your-repositories), it could be quite easy to fork, translate, update, submit - with a proper tutorial. Apart from this, we might also add a basic interactive translation feature to Mapper itself - this could help those people which need to find the context.

**Comment by Abbe98** [comment]
First of investigating Qt Translator->Github workflow then.

**Comment by dg0yt** [comment]
Applied for a [hosted](https://hosted.weblate.org/projects/) [Weblate](https://weblate.org/en/) project.

**Comment by dg0yt** [comment]
Here we go: https://hosted.weblate.org/projects/openorienteering/mapper/

**Comment by dg0yt** [comment]
Update https://github.com/OpenOrienteering/mapper/wiki/Translation.
Feel free to make precise suggestions where I should add Weblate links (homepage, app, manual).

**Comment by dg0yt** [comment]
I did a lot of technical fixes to translations, based on the checks in Weblate. In addition, it gives a good feedback on the source strings, such as potential plural strings. 

@nijel Very thankful for being hosted there! Kai.
