### ISSUE TITLE
Size of area element in dash symbol depend from line type and direction angle

### ISSUE THREAD

**Issue by Symbian9** [OpenOrienteering/mapper#664]
Here is a bug with dash in "Line symbol": area element in Dash symbol depend from angle (its happened on straight lines, but not on curves)
![screenshot coming soon](http://pasteall.org/pic/show.php?id=102078)

Zipped OMAP file here:
- ftp://ftp.lviv.farlep.net/symbian/oom-dash-area-bug.zip

**Comment by dg0yt** [comment]
I understand that this behaviour is not desired in above example, and its surprising in that use case. However, this behavior is intentional with regard to where it is used: The power line symbols. I'm not even sure if it is the right solution for 516 Power line, but is mandatory for 517 Major power line.

In summary, the current behavior seems to be tailored for one particular use case rather than the general case, and this bug report is a valid one, although not high-priority for orienteering maps.

**Comment by Symbian9** [comment]
> I understand that this behaviour is not desired in above example, and its surprising in that use case. However, this behavior is intentional with regard to where it is used: The power line symbols. I'm not even sure if it is the right solution for 516 Power line, but is mandatory for 517 Major power line.

@dg0yt, I think, that for "Power line" effect it would be usefull add <b>checkbox in line settings dialog</b>, like it already implemented for "Always oriented to north (not rotatable)"!

Also found some other bugs:
* "Dash Symbol" ignore  "Always oriented to north (not rotatable)" option.
![Dash to North](http://pasteall.org/pic/show.php?id=107719)

* in combined symbol based on line with "Dash Symbol",  dash symbols lost!
![Dash in Combined](http://pasteall.org/pic/show.php?id=107720)

**Comment by dg0yt** [comment]
Why not attach the test files in a ZIP archive?

**Comment by Symbian9** [comment]
Attachment sent via email now.
