### ISSUE TITLE
exporting pdf: template layer is pushed below the map layer

### ISSUE THREAD

**Issue by otoomet** [OpenOrienteering/mapper#708]
I use Mapper 0.6.3.  I want to print a map with individual tree template layer on top of the existing map.  However, when exporting, the map becomes the top layer and the template is not visible except in the white (405) area.

The mapper window looks like this.  Note the gray trees on the yellowish background (404):
![mapper](https://cloud.githubusercontent.com/assets/13666380/16181197/57a395a0-364c-11e6-957f-6ab8e17cbe3e.png)

When I open the export window, the trees on the rough open land are still visible:
![export](https://cloud.githubusercontent.com/assets/13666380/16181213/92844d90-364c-11e6-8a67-6e4586bbfe70.png)

However, in the final pdf the trees are only visible on the white:
[final_pdf.pdf](https://github.com/OpenOrienteering/mapper/files/322595/final_pdf.pdf)

**Comment by dg0yt** [comment]
Sorry, this doesn't work in vector graphics mode. You face the reason for the "Template appearance may differ" warning in the 2nd screenshot. There may be raster images with true transparency, but in general it requires raster graphics mode to draw a raster template on top of the map. Otherwise the raster template will completely cover the vector data, instead of blending. Printers work different, especially on three different platforms... We can't simply apply 25% opacity.

**Comment by dg0yt** [comment]
To add some inconsistency: raster templates are drawn below the map layer only if their opacity is less than 100%...

**Comment by Abbe98** [comment]
> To add some inconsistency: raster templates are drawn below the map layer only if their opacity is less than 100%...

@dg0yt something for the documentation?

**Comment by dg0yt** [comment]
https://bugreports.qt.io/browse/QTBUG-70752, https://bugreports.qt.io/browse/QTBUG-60677
