### ISSUE TITLE
Rotate tool "destruct" objects

### ISSUE THREAD

**Issue by 999999333** [OpenOrienteering/mapper#743]
### Steps to reproduce
1. create some polygon, on more complex its more visible
2.select it and rotate it a few times 
3.

### Actual behaviour
When I click R (rotate) and rotate some object it disort somehow. I dont change point of rotation. Maybe it happen more often when i zoom during rotation.

### Expected behaviour
It should rotate without losing its shape

### Configuration
Mapper Version: 0.6.3
Operating System: Windows 10
Before rotation
![beforeratation](https://cloud.githubusercontent.com/assets/4051127/17646013/eeae2140-61b7-11e6-9109-3078e7252d1b.PNG)
After few spins
![after](https://cloud.githubusercontent.com/assets/4051127/17646012/eea91c54-61b7-11e6-9233-c190354019b2.PNG)

**Comment by dl3sdo** [comment]
I can confirm your observation. This can also be shown by using the 'Measure lengths and areas' tool.

However, be aware that with every rotation the coordinate points of the object are subject to trigonometric operations and there will always be a rounding due to the limitations of floating point variables. The effects thus increases by the number of rotations applied.

**Comment by dg0yt** [comment]
Actually this is not a floating point issue but due to the discretization of coordinates to 0.001 millimeters. The best we can do is to improve the operation of this until the tool and/or the edited objects are changed.

**Comment by dg0yt** [comment]
Maybe this can be approached by drawing the selection's graphical primitives in a rotated coordinated system during the operation, instead of continuously regenerating the primitives from rotated coordinates.
