### ISSUE TITLE
Map selection doesn't always show up when printing

### ISSUE THREAD

**Issue by kjetilk** [OpenOrienteering/mapper#747]
I'm sometimes experiencing problems when printing, but it isn't entirely reproducable.

### Steps to reproduce sometimes...:
1. Open a map with a course, made with the new simple symbol set and a single template
2. Open another, and another... I have 7-8 courses open
3. Select Print...
4. Have A4 sheet paper.

### Actual behaviour
The print box appears to the right, but the map disappears entirely at the same time, thus preventing selection of a good selection of the map. If I hit "Preview...", a preview of the map will be generated, but contains a subset of the map I can't use.

### Expected behaviour
The common behaviour that the map doesn't disappear, but instead is framed with a selection box so that I can select the print region. Often this works as expected, but often it doesn't. I don't know which of the steps above has to be taken, as I have not been able to reproduce this reliably. I'll report more if I find out more, but it is nice if you could try to check it out. :-)

### Configuration
Mapper Version: 0.6.4
Operating System: Linux Mint 17.1

**Comment by kjetilk** [comment]
Hmmm, noticed another thing: When things go wrong, the zoom is at 0.0625x. Also, it doesn't seem to matter how many files I have open.

**Comment by dg0yt** [comment]
I am not yet able to reproduce this issue. The only small annoyance I observe is that "Show templates" is not checked by default for the course design.

What happens when you select "View" > "Show whole map"? 

When selecting "Print..."  the view scale is changed so that it covers the map and the visible templates, and the resulting area is centered. 0.0625x is the minimial zoom value. So when you get this zoom value  and don't see anything, this indicates that map and templates didn't fit on the screen in this zoom setting. Either is there an map or template object at an unexpected position, or there is a bug in determining the relevant area.

**Comment by kjetilk** [comment]
> What happens when you select "View" > "Show whole map"? 

Aha, there's something there. That too zooms to the minimal zoom value, and the map is not discernible. If I pan around and zoom in and out, I see a green letter 'A', but the map is not there. So, it seems the problem is not in the printing, but something about the map area.

**Comment by kjetilk** [comment]
Ah, found the map! :-) The position was out to -14000 mm or something like that... Panning back to around origin, I found it. The upper right corner of the visible map is at about 40,-160mm, so it is rather odd. So, is the whole problem here that the map comes with a huge area and an odd coordinate system?

**Comment by dg0yt** [comment]
AFAICT from your description, the problem is a lonely green 'A' in a place where it doesn't belong.

**Comment by kjetilk** [comment]
Heh, right! So, I'll just close this, then. Sorry for the fuzz!
