### ISSUE TITLE
Font sizes not correct after saving to OCD

### ISSUE THREAD

**Issue by krticka** [OpenOrienteering/mapper#759]
### Steps to reproduce
1. Open any OMAP file in Mapper and add text symbol, for example Control number with font size 4 mm. 
2. Save file to OCD format.
3. Open in OCAD and check font size for Control number. Size is now 2.86 mm.

### Actual behaviour
Font sizes are not correct after saving to OCD.

### Expected behaviour
Font sizes should be the same as in OMAP file.

### Configuration
Mapper Version: 0.6.5
Operating System: Win 8.1

**Comment by dg0yt** [comment]
The sizes are correct, effectively. 

However, according the OCAD wiki, OCAD displays the *character height* in addition to the *font size*. This is how the height of text is given in the ISOM. Mapper displays the *font size* as used in other applications but using millimeters instead of points. Mapper provides a separate "Determine size..." tool to determine the correct font size from the height of an arbitrary letter.

**Comment by dg0yt** [comment]
Did you check my answer?

I could imagine changing the user interface like this:
![text-symbol-settings](https://cloud.githubusercontent.com/assets/13567791/18931126/2379f714-85cb-11e6-9923-502d9659b694.png)
- Only pt for font size
- Letter and its height moved from extra dialog to below font size.

**Comment by krticka** [comment]
Too busy last week, sorry!

The interface looks perfect. I think that rounding of font size to hundredths can cause inaccuracies as I found in OCAD file format: "The unit of all dimensions is 0.01 mm, except for the font sizes which are measured in 0.1 typographical points". 
Am I wrong?

**Comment by dg0yt** [comment]
Mapper stores font size in millimeters with three decimal places internally. This should give sufficient precision to represent the font size from OCD (0.1 pt), from the font size input field (0.01 pt), or from the letter height input field (0.01 mm). Note that non of the three can be stored without conversion!

Rounding because of limited input precision takes place only when you change values - but the given input precision should be more than enough.

There are many places which involve rounding when saving as OCD. Normally the error from one-time rounding is negligible. When the precision is 0.1 pt (~0.035 mm), the maximum error is 0.05 pt (~0.018 mm).
