### ISSUE TITLE
Object not found!

### ISSUE THREAD

**Issue by fioru89** [OpenOrienteering/mapper#768]
All exe-file for Windows: object not found!

**Comment by dg0yt** [comment]
Please be a little bit more verbose in reporting issues. It took me some time to figure out that you were (probably) following the download links from www.openorienteering.org to the [v0.6.5 release page](https://github.com/OpenOrienteering/mapper/releases/tag/v0.6.5). The v0.6.5 download links for Windows no longer work because [Mapper v0.6.6](https://github.com/OpenOrienteering/mapper/releases/tag/v0.6.6) was released just a few hours before your post. Now www.openorienteering.org is updated, too.
