### ISSUE TITLE
Android crashed when pressing save button and file  xxx.omap.E19162 generated

### ISSUE THREAD

**Issue by Tiekku** [OpenOrienteering/mapper#781]
### Steps to reproduce
1. The Phone/application was crashed. Application restart shows that there is 2-version of the map 
2. After restart, I do not remember save correct version of map and continued work about 3 hours.
3. No autosave at all during this time?!?!?!?
4. When save hole android crashed and make file map.omap.E19162
### Actual behaviour

File was not saved and Phone restarted after pressing save button.
Auto save do not work at all
### Expected behavior

Phone do not restart after pressing save button and file is saved.
Autosave working 
That E file explanation!  
### Configuration

Mapper Version:  Android 0.6.0
Operating System:  Samsung note2, Andoid 4.4.2

**Comment by dg0yt** [comment]
I won't investigate crashes in Mapper 0.6.0. The current version is 0.6.6. Apart from this, the error may be in the phone (hot CPU, bad RAM, bad storage). Otherwise the Linux-based Android shouldn't restart from activities in a simple app. 

Saving the map doesn't put special load on the CPU or RAM, but it writes a temporay file (yes, map.omap.E19162, for example) first and only then replaces the original file. And of course the autosaved snapshot will be removed after successfull saving. Saving on a full storage could trigger some rough edges in the operating system. It would be good to know if the crash was in a situation of full storage. Note that the saved file may be significantly larger than the original file after some hours of work due to the saving of undo information.

Map.omap.E19162 should contain at least part of your work. However, it might need some editing before it can be loaded again.

**Comment by Tiekku** [comment]
Who can help that E-file editing?  Any instructions what to do?

**Comment by dg0yt** [comment]
I can help, of course. You can send the file via e-mail (see my profile). I could also offer a private space for upload. 

The file might be truncated. Since it is based on XML, making it loadable means closing any open XML tags at the end. There might be XML editors which can help with that.

**Comment by dg0yt** [comment]
Please reopen if you want to provide more information.
