### ISSUE TITLE
Document that Mapper is available in Debian/Ubuntu

### ISSUE THREAD

**Issue by kjetilk** [OpenOrienteering/mapper#809]
I think it is worth documenting that Mapper is available in Debian and Ubuntu as openorienteering-mapper.
Normal caveats apply, of course, that the stable distribution has a (long) period of stability, where the package does not follow upstream releases. But that's how many people like it, including myself. 

It is in Ubuntu from 16.10 and in Debian Stretch, which is due to freeze shortly for release next year.

**Comment by dg0yt** [comment]
It is already mentioned for Arch and Debian in the [v0.6.6 release](https://github.com/OpenOrienteering/mapper/releases/tag/v0.6.6) and also for Ubuntu and Slackware in the [target systems wiki page](https://github.com/OpenOrienteering/mapper/wiki/Target-systems). 

I did my best to quickly respond to issues reported by the Debian package maintainer @gaudenz here, I triggered an update of the watchfile so that the availability of 0.6.6 is visible in the package tracker, I uploaded a screenshot, and I responded to personal e-mails. Unfortunately, my impression is that the Debian package maintainer is not very active wrt to Mapper. *Thus I will probably remove the Debian mention from the release pages. It is a disservice at the moment.* OBS provides a sufficient infrastructure to distribute and receive updated versions.

**Comment by kjetilk** [comment]
Ah, I was looking for it in the OBS, but I suppose it isn't where it can't be mentioned. Anyway, it has been updated in Debian now, and I think it is important to have it there. Think, for example, about schools where putting in additional sources most likely would not be done, but disting Mapper from official Debian archives is a trivial matter. You could potentially have thousands of kids exposed to map drawing through that. 

But yeah, I suppose the mention is sufficient, so, I'll close.

**Comment by gaudenz** [comment]
I have updated the package in Debian a few days ago. I'll try to be quicker next time. Do you have any kind of announcement mailinglist beside the watch file where I can get notifications about new releases and a short list of changes to see how important an upload is?

I suggest you mention both sources on your wiki page. The OBS packages as always up to date but automatically built and less integrated into the system and the Debian/Ubuntu packages from the main repositories as manually built and checked.

**Comment by dg0yt** [comment]
We do not have a public announcement mailing list. (Github does't offer mailing list, and I don't want to promote Sf at the moment.) The best thing I can imagine is setting up an issue which maintainers and users can subscribe to. I would lock this issue for conversations to limit noise. 

Our release notes on Github list the major changes and fixes. They have extra links to all fixed issues and to all changes in git. So far, almost all releases contained important bugfixes. For Debian stable, I could help to identify changes which might need to be backported once the distribution doesn't want to follow the latest release.

While there are some things which I will not do in the OBS packages (like splitting binary artifacts and data), there is no reason why they should be "less integrated into the system", apart from the extra repository.

**Comment by dg0yt** [comment]
@gaudenz We have a new release, https://github.com/OpenOrienteering/mapper/releases/tag/v0.6.7. Again, it fixes some nasty errors in opening files. Probably this will be the last release in the v0.6 series.

**Comment by gaudenz** [comment]
Kai Pastor <notifications@github.com> writes:

> @gaudenz We have a new release,
> https://github.com/OpenOrienteering/mapper/releases/tag/v0.6.7. Again,
> it fixes some nasty errors in opening files. Probably this will be the
> last release in the v0.6 series.

I updated the package in Debian. Debian unstable is now at 0.6.7 and
testing should get it in 10 days.

Gaudenz
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/OpenOrienteering/mapper/issues/809#issuecomment-268732723
-- 
PGP: 836E 4F81 EFBB ADA7 0852 79BF A97A 7702 BAF9 1EF5

**Comment by kjetilk** [comment]
Great work and great stuff! Then, we're pretty sure that 0.6.7 will be in Stretch, and I think that's a very good solution! :-)

**Comment by dg0yt** [comment]
I recently removed the information that Mapper is available on Debian.
openorienteering-mapper in Debian hasn't been updated since 0.7.0. It is about to be removed from Debian testing today because this version fails to build from source with newer version of libpoppler which we don't use but which is pulled in via libgdal. (It is not really our fault, and still we quickly took measures to fix this and similar issues.)

Packages for Debian and Ubuntu users continue to be available from 
https://software.opensuse.org//download.html?project=home%3Adg0yt&package=openorienteering-mapper
(built at
https://build.opensuse.org/package/show/home:dg0yt/openorienteering-mapper)

**Comment by dg0yt** [comment]
https://tracker.debian.org/pkg/openorienteering-mapper
