### ISSUE TITLE
Compile error with Clang 3.4

### ISSUE THREAD

**Issue by sikmir** [OpenOrienteering/mapper#847]
Build error:
```
/locale_t.cpp:68:23: error: no matching constructor for initialization of 'QString'
        auto test_filename = QString { QLatin1String("some_dir/") + test_basename + QLatin1String("_eo.qm") };
                             ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/qt5/QtCore/qstring.h:223:14: note: candidate constructor not viable: no known conversion from 'QStringBuilder<typename QConcatenable<QStringBuilder<QLatin1String, QLatin1String> >::type, typename QConcatenable<QLatin1String>::type>' to 'const QChar *' for 1st argument
    explicit QString(const QChar *unicode, int size = -1);
             ^
/usr/local/include/qt5/QtCore/qstring.h:224:5: note: candidate constructor not viable: no known conversion from 'QStringBuilder<typename QConcatenable<QStringBuilder<QLatin1String, QLatin1String> >::type, typename QConcatenable<QLatin1String>::type>' to 'QChar' for 1st argument
    QString(QChar c);
```
Full description & log in FreeBSD Bugzilla: [Bug 214758](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214758).
OOMapper port: [sikmir/freebsd-ports/graphics/openorienteering-mapper](https://github.com/sikmir/freebsd-ports/tree/6bf8d6653d6f6589993fe9651ea14707d9c6ebbe/graphics/openorienteering-mapper)

### Notes
Build  is OK with Clang 3.8.0 (FreeBSD 11.0).
[C++ Support in Clang](http://clang.llvm.org/cxx_status.html):

> Clang 3.4 and later implement all of the ISO C++ 2014 standard.

### Configuration
Mapper Version: 0.6.8
Operating System: FreeBSD 10.3
Clang: 3.4.1
Qt: 5.7.1

**Comment by dg0yt** [comment]
This line uses QStringBuilder (by means of `operator+)` to construct a QString which goes into an auto (needing the explicit `QString` cast from QStringBuilder). There are QString copy and move constructors, and there is `QStringBuilder::operator QString()`. But the BSD bug report shows that the compiler still doesn't find a conversion from `QStringbuilder` to `QString&&` or `QString&`, maybe because a temporary is involved here. I guess it is a bug in the older compiler.

~~~
/usr/local/include/qt5/QtCore/qstring.h:233:12: note: candidate constructor not viable: no known conversion from 'QStringBuilder<typename QConcatenable<QStringBuilder<QLatin1String, QLatin1String> >::type, typename QConcatenable<QLatin1String>::type>' to 'QString &&' for 1st argument
    inline QString(QString && other) Q_DECL_NOTHROW : d(other.d) { other.d = Data::sharedNull(); }
           ^
[....]
/usr/local/include/qt5/QtCore/qstring.h:900:17: note: candidate constructor not viable: no known conversion from 'QStringBuilder<typename QConcatenable<QStringBuilder<QLatin1String, QLatin1String> >::type, typename QConcatenable<QLatin1String>::type>' to 'const QString &' for 1st argument
inline QString::QString(const QString &other) Q_DECL_NOTHROW : d(other.d)
                ^
~~~

As a workaround, I would suggest the following change:
~~~
--- test/locale_t.cpp
+++ test/locale_t.cpp
@@ -65,7 +65,7 @@ void LocaleTest::testEsperantoTranslationUtil()
 	auto test_basename = QLatin1String("LocaleTest");
 	TranslationUtil::setBaseName(test_basename);
 	
-	auto test_filename = QString { QLatin1String("some_dir/") + test_basename + QLatin1String("_eo.qm") };
+	QString test_filename = QLatin1String("some_dir/") + test_basename + QLatin1String("_eo.qm");
 	QCOMPARE(TranslationUtil::languageFromFilename(test_filename), TranslationUtil::languageFromCode(eo));
 }
 
~~~

But I will not merge this change even if it works, and there may be more spots like this.

**Comment by sikmir** [comment]
@dg0yt Sure, there is no need for fix in upstream at all, since it perfectly works with Clang>=3.8.0 (at least). I just think it's worth to point out the minimum supported version for Clang in the wiki. For now I've tried Clang 3.5.x, it doesn't compile OOM either.

**Comment by Symbian9** [comment]
> Sure, there is no need for fix in upstream at all, since it perfectly works with Clang>=3.8.0 (at least). I just think it's worth to point out the minimum supported version for Clang in the wiki. For now I've tried Clang 3.5.x, it doesn't compile OOM either.

Yeah, but do not increase CLangversionvdependency for 0.6.x branch (without GDAL support)

**Comment by sikmir** [comment]
> Yeah, but do not increase CLang version dependency for 0.6.x branch (without GDAL support)

@Symbian9 What do you mean? It primarily affects only FreeBSD (where clang is default compiler) and "USES+=compiler:c++14-lang" in port's Makefile fixes it.
