### ISSUE TITLE
Missing ISOM 2017 symbol sets

### ISSUE THREAD

**Issue by lpechacek** [OpenOrienteering/mapper#856]
[International Specification for Orienteering Maps (ISOM) 2017 has been published](http://orienteering.org/international-specification-for-orienteering-maps-isom-2017-has-been-published/
)

> ...
> For IOF events between 1 May and 31 December 2017, both ISOM 2000 and ISOM 2017 could be accepted, but which map standard is used at the event must be clearly stated in the Bulletin(s) for the event. For all events after 1 January 2018, ISOM 2017 should be used unless there are contractual limitations which would prevent this.
> ...

If there is interest in the topic, I can give a helping hand in adjusting the symbol sets.

**Comment by yevhenmazur** [comment]
+1 It's time to add ISOM 2017 symbol set under version control and include it in unstable build.

**Comment by dg0yt** [comment]
There is a lot of interest, recorded in #612. A pull request would be welcome. Please start with a copy of "symbol sets/src/ISOM_15000.xmap" to "symbol sets/src/ISOM_2017_15000.xmap", maybe in a separate commit so that subsequent editing becomes easier to review.

I will close this issue in favour of #612.

**Comment by lpechacek** [comment]
I see. I must have overlooked #612 when searching for existing ISOM related issues. Sorry for the noise.
