### ISSUE TITLE
ISOM 2017

### ISSUE THREAD

**Issue by 999999333** [OpenOrienteering/mapper#861]
Bellow attached beta of ISOM 2017 symbol set. Need more work on color order but it should be usable in this state. Based on yevhenmazur  work, added minimal dimensions, fixed some symbols sizes, symbol order... 

It needs to:
1. Make spot symbols for contour knolls,.. 
2. Play with color order (Narrow rides)

Have fun! 😃 

[ISOM2017_15000.zip](https://github.com/OpenOrienteering/mapper/files/948285/ISOM2017_15000.zip)

**Comment by havatv** [comment]
Line colour of symbol 416.1 shall be "Green 100 %/Black 50 %".  Currently it is "Green".

**Comment by yevhenmazur** [comment]
Both fixed in https://github.com/OpenOrienteering/mapper/pull/872/commits/3d2661aae4fd4eccf55d65d9ab53bc0c7b6fbde6

**Comment by dg0yt** [comment]
Worked on in #872. Closing here.

**Comment by Zerbembasqwibo** [comment]
Time to open up again. ISOM 2017 will be changed due to descision today.

Changes here: https://orienteering.org/wp-content/uploads/2018/11/ISOM-2017-corrections-approved-2018-11.pdf

It will be very confusing if it doesnt change name to ISOM 2018....

**Comment by dg0yt** [comment]
Better open a new issue on "ISOM 2017 rev. 2018-11"...

**Comment by mlerjen** [comment]
... or "ISOM 2019"
![image](https://user-images.githubusercontent.com/15611653/49073656-3e766300-f233-11e8-8fa9-47c7180c7a94.png)

**Comment by Zerbembasqwibo** [comment]
I would prefer this name covention:

ISOM 2017:1 (original version) ISOM 2017:A1 (amendment 1) (publish here all
changes and additions) ISOM 2017:2 (consolidated version; original that has
been modified according to A1)

Use new year number only when major updates are done. So many documents,
contracts, map info texts etc to update otherwise.




tisdag 27 november 2018 skrev mlerjen <notifications@github.com>:
