### ISSUE TITLE
On some Android devices, Mapper 0.7.0 crashes when loading JPEG templates

### ISSUE THREAD

**Issue by Zerbembasqwibo** [OpenOrienteering/mapper#891]
### Steps to reproduce
1. Open an old, at least 0.6.8-OOM-file on you Android with 0.7.0

### Actual behaviour
Program crash and close

### Expected behaviour
Open file, convert to 0.7.0, or give some explanation it's not possible bacause reasons

### Configuration
Mapper Version: 0.7.0
Operating System: Android

**Comment by dg0yt** [comment]
I didn't observe any such crash. If it is not a particular file, provide information about your Android device.

**Comment by dfgeorge** [comment]
I have the same issue on a samsung 10.1 inch note tablet running android 4.4.2. 1 can open ocad files ok but not old oom files.

**Comment by dg0yt** [comment]
Please confirm:
Do only 0.6.8 files trigger the crash, not files from 0.7.0? There are two 0.7.0 example files included.

(It does not crash on any of my devices, Android 4.4, Android 6.0.)

**Comment by Zerbembasqwibo** [comment]
I have Android 5.1. Yes, 0.7.0 files works fine, tried example file and an other tranferred from computer.

**Comment by dg0yt** [comment]
Please send me a minimal offending file. See https://github.com/dg0yt for direct e-mail.

**Comment by dfgeorge** [comment]
Seems it might be a templates causing it. I just tried to open an old file with templates and it crashed. Renamed the template directory so it didnt find the templates and it opened.

**Comment by dg0yt** [comment]
If it is one of the formats now handled by GDAL (GPX, DXF, OSM), you can disable the new importer in the settings. I wouldn't be surprised if the new importer consumes more memory.

**Comment by dfgeorge** [comment]
A single 500kb georeferenced jpeg template causes it to crash. I have emailed an example

**Comment by dg0yt** [comment]
Even with your files, I can open the map without problems on a low-end Android 6.0 device (Sunny Wiko). This means I still cannot reproduce the issue. I will test in the emulator in the next days. 

JPEG support in Mapper is unchanged. However, there is one significant change:
In Mapper 0.6 for Android, Windows and Mac, we used libjpeg 8c which is bundled with Qt. In Mapper 0.7 for Android, Windows and Mac we [build and distribute libjepg-turbo 1.5.1](https://github.com/OpenOrienteering/superbuild/blob/master/libjpeg-turbo-1.5.1-2.cmake) instead. There is [no indication of related fixes after this release](https://github.com/libjpeg-turbo/libjpeg-turbo/compare/1.5.1...master).

For now, how far do you get before the crash? Does it crash when there is only the single vegetation.jpg template file available? (Mapper loads hidden templates so they would occupy memory.) If it crashes, do you see the dialog box with warnings for missing templates? When you reopen the file after the crash, do you get a warning that the file triggered a crash before?

**Comment by dfgeorge** [comment]
The only template i have in the directory is vegetation.jpg. 0.6.8 worked
with all the templates, some of which are large aerial photos.

It crashes real quick with a "unfortunately orienteerer mapper has stopped"
message. No other messages.

If i try and open it again it warns me it crashed last time. Are there any
logs?

Cheers,

Dave

On 16/06/2017 5:22 PM, "Kai Pastor" <notifications@github.com> wrote:

Even with your files, I can open the map without problems on a low-end
Android 6.0 device (Sunny Wiko). This means I still cannot reproduce the
issue. I will test in the emulator in the next days.

JPEG support in Mapper is unchanged. However, there is one significant
change:
In Mapper 0.6 for Android, Windows and Mac, we used libjpeg 8c which is
bundled with Qt. In Mapper 0.7 for Android, Windows and Mac we build and
distribute libjepg-turbo 1.5.1
<https://github.com/OpenOrienteering/superbuild/blob/master/libjpeg-turbo-1.5.1-2.cmake>
instead. There is no indication of related fixes after this release
<https://github.com/libjpeg-turbo/libjpeg-turbo/compare/1.5.1...master>.

For now, how far do you get before the crash? Does it crash when there is
only the single vegetation.jpg template file available? (Mapper loads
hidden templates so they would occupy memory.) If it crashes, do you see
the dialog box with warnings for missing templates? When you reopen the
file after the crash, do you get a warning that the file triggered a crash
before?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/OpenOrienteering/mapper/issues/891#issuecomment-308959094>,
or mute the thread

**Comment by dg0yt** [comment]
> I have the same issue on a samsung 10.1 inch note tablet running android 4.4.2.

I realized that this might be a 10.1 inch version of my other device, and bingo! JPEG template crash reproduced. I do have some ideas what to try out.

**Comment by dg0yt** [comment]
In the debugger, the JPEG library complained about the application code expecting different data structures. After some experimentation, I assume that the application doesn't get the libjpeg.so library we build and use for build but a preinstalled one. A [change in library search order around level 23](https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md) might explain why the issue could not be observed on Android 6.0 devices.

I attempted to use a shared library because it is used in GDAL and in Qt. I don't have the time to investigate how to make them both use a different soname for this library. The only feasible change for now is a static (non-shared) libjpeg.a even if this means duplication and increased binary size.

**Comment by dg0yt** [comment]
Please try (v0.7.0.1)[https://github.com/OpenOrienteering/mapper/releases/tag/v0.7.0.1].

**Comment by Zerbembasqwibo** [comment]
I am really impressed! It works as great as usual now! :) Have a very nice
Saturaday evening!

2017-06-17 18:46 GMT+02:00 Kai Pastor <notifications@github.com>:

**Comment by dg0yt** [comment]
Thanks for feedback. The initial post didn't really provide much hints, and I would have appreciated catching this error with one of the release candidates.
