### ISSUE TITLE
Build error: ‘make_unique’ is not a member of ‘std’

### ISSUE THREAD

**Issue by probonopd** [OpenOrienteering/mapper#897]
### Steps to reproduce
1. Use Ubuntu 14.04
2. Try to compile Mapper

### Actual behaviour
`crs_template_implementation.cpp:45:14: error: ‘make_unique’ is not a member of ‘std’`

### Expected behaviour
Compiles

### Configuration
Mapper Version: latest from git
Operating System: Ubuntu 14.04

Build logfile:
https://api.travis-ci.org/jobs/248041067/log.txt?deansi=true

**Comment by dg0yt** [comment]
Actually, this is expected behaviour for stock Ubuntu 14.04 because 

> -- The CXX compiler identification is GNU 4.8.4

and gcc 4.8 doesn't support C++14 which is now required to build Mapper.

Cf. https://github.com/OpenOrienteering/mapper/blob/v0.7.0/INSTALL.md
and https://github.com/OpenOrienteering/mapper/wiki/Target-systems#limited-to-06x-releases

**Comment by probonopd** [comment]
Thanks @dg0yt my bad, the `#limited-to-06x-releases` table is really best practice for documentation.

**Comment by probonopd** [comment]
__Note:__ I was able to compile this on Ubuntu 14.04 using

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get -y install gcc-4.9 g++-4.9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
```
