### ISSUE TITLE
F3 and F4 keys does not work

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#905]
### Steps to reproduce
1. Open / Create new map
2. Try to toggle Baseline view or Overprinting simulation with function keys.

### Actual behaviour
Nothing happens

### Expected behaviour
Toggling of Baseline view or Overprinting simulation mode 

### Configuration
Mapper Version:
- 0.7.0 - **not** reproduced
- 0.7.20170720 - reproduced
- 0.7.20170726 (current build) - reproduced

Operating System: All platforms (Windows and Linux tested)

**Comment by Symbian9** [comment]
Also, @999999333 reported to me that there is issue with other shortcuts

> Fill tool shortcut ctrl+f colides with "Find objects" window - so setup another shortcut to Fill function (maybe ctrl+E)

**Comment by dg0yt** [comment]
F4 is working if the map has spot colors. (Requires OMAP.)

Both F3 and Ctrl+F are currently consumed by the find-objects feature. These are common standard shortcuts for "Find..." and "Find next", and indeed these actions are configured to use standard behaviour in https://github.com/OpenOrienteering/mapper/blob/master/src/gui/map/map_find_feature.cpp#L51 (`QKeySequence::Find`, `QKeySequence::FindNext`).

Since a shortcut customization dialog probably won't exist very soon, an alternative solution has to be found now.
