### ISSUE TITLE
Unable to print a map under certain conditions

### ISSUE THREAD

**Issue by yevhenmazur** [OpenOrienteering/mapper#933]
### Steps to reproduce
1. Open not empty map with at least one template
2. Set map opacity less than 100%
3. Open Print window and set 'Show templates' checkbox
4. Print

### Actual behaviour
Only template is visible on printing

### Expected behaviour
Map and template are visible on printing. If we cannot just apply opacity to vector layer (https://github.com/OpenOrienteering/mapper/issues/708), Mapper should warn the user, ignore the opacity settings and print the map as it would be 100% opacity. 

### Configuration
Mapper Version: All versions (0.6.8 - current build tested)
Operating System: Windows only

**Comment by dg0yt** [comment]
Can you provide a minimal test file? Does it happen in preview, too?

**Comment by yevhenmazur** [comment]
The preview looks good.
Here is the test file
[933.zip](https://github.com/OpenOrienteering/mapper/files/1240164/933.zip)
Reproduced only when template is above the map.

**Comment by dg0yt** [comment]
Okay, this occurs on Windows only... printing is a minefield.

Some time ago [I added quite a hack](https://github.com/OpenOrienteering/mapper/commit/0779b8ff5a36a1aab2230c186dd34e11a1c1a3d2#diff-db9e3415f5904aa7b3b48f7f59a3dacbR829) which made Qt use a higher resultion than reported by the printer. Without this trick all coordinates would [suffer from discretization](https://sourceforge.net/p/oorienteering/tickets/241/attachment/win-print-resolution.png). If I disable this code, the examples prints fine.

So how does it go wrong? I can't explain completely, but what I found is that Qt itself starts drawing the vector data into raster images in order to deal with opacity. I guess that either raster image generation or output get confused by the trick.

Anyway, the whole distinction vector vs. raster mode becomes obsolete with opacity on Windows...
