### ISSUE TITLE
Brown color in Paint-on-template is too pale.

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#944]
Brown color in Paint-on-template is too pale. The scribbles are very hard to see. I hardly use it because of that.
Please make brown darker or add more colors.

Mapper Version: 0.7.0 (Android App)

**Comment by mlerjen** [comment]
I want to add my perspective here. Of course you cannot make it right to everybody...

What I would need is a set of distinct colors at least  under outdoor conditions. The way it is now purple, the darker brown and red are pretty alike to each other.  Using either red or brown for contours the remaining two colors of this group are not useful for mapping area features.


![image](https://user-images.githubusercontent.com/15611653/39677082-818c0d34-5175-11e8-957f-3f4b00d90a69.png)

That way I stopped using brown since the update. So the mappers who like to fill areas have rather lost than won a color.. (the light brown, or a cyan with a slightly darker green would work better for me). Just saying...

**Comment by ollesmaps** [comment]
I on the contrary started using it more :) Bigger color palette would be a solution (#945).
