### ISSUE TITLE
Restored template files not found after saving and reopening a map file

### ISSUE THREAD

**Issue by dfgeorge** [OpenOrienteering/mapper#955]
### Steps to reproduce
I have a number of high-res templates which will not all load into memory at once. I moved some of the templates (for second days mapping) into another folder, Mapper worked great.

Next day I swapped the templates to work another map area. Mapper did not load the templates that were now replaced in the correct folder, I could not find a way to fix in the program.

Loaded the map on the PC, saved, all worked (lucky I had the PC :-)

### Expected behavior
I expect the templates to load when put back in the correct folder. Seems to work on the PC version.

### Configuration
Mapper Version: Android 0.7.91 (does the same with 0.7)
Operating System: Android 6 (0.7.91) and Android 4.2 (0.7)

**Comment by dg0yt** [comment]
When Mapper loads a map, it tries hard to find the templates, in the following order:

1. by the relative path stored in the OMAP file
2. by the absolute path stored in the OMAP file
3. directly in the map's folder.

https://github.com/OpenOrienteering/mapper/blob/7b79075f41ed81af68e5efc3ec2d0d24aea62c7c/src/templates/template.cpp#L516-L560

There is no automated testing yet. Before I spend more time on this, I would like to ask you to verify that the issue is not on your side. Maybe you can provide a minimal example set of files, and attach it as ZIP.

**Comment by dfgeorge** [comment]
Example file attached contains a map file (with one large lake) and a templates directory with two templates in.

To reproduce what I did:

Copy to android device, map should open OK.
Move one of the templates to the holding directory (or somewhere else).
Open map, edit, save.
Move the template back to the template directory.
OOMapper did not find the template when opened. 
[issue955.zip](https://github.com/OpenOrienteering/mapper/files/1295509/issue955.zip)

Move map file back to PC and map opens OK with templates.

**Comment by dg0yt** [comment]
Thanks for the files. Reproducible on desktop, too. (Well, this is what I expected.) This make debugging much easier. 

Saving the edited file to a different name and comparing the result confirms what I guessed: For the missing file, the stored relative path is empty, rather than preserved. The absolute path points to the desktop location (starting with a windows drive letter). Thus both the 1st and the 2nd candidate location fail on reopening (and the 3rd doesn't have the path either).

**Comment by dg0yt** [comment]
Change 1489e17 breaks the corresponding TemplateTest on build.opensuse.org:

~~~
[  286s] FAIL!  : TemplateTest::templatePathTest() Compared values are not the same
[  286s]    Actual   (warnings.size()): 0
[  286s]    Expected (std::size_t(1)) : 1
[  286s]    Loc: [/usr/src/packages/BUILD/test/template_t.cpp(119)]

**Comment by dg0yt** [comment]
Now (ea4cdd0e) fixed also for Debian builds.
