### ISSUE TITLE
Rectangle around selected objects and nodes clash

### ISSUE THREAD

**Issue by ollesmaps** [OpenOrienteering/mapper#980]
### Steps to reproduce
In Edit objects mode you easily move object even if you want to move just a node.  Start, finish (and other nodes on rectangle) do problems.

### Expected behaviour
In Edit objects mode put the rectangle around selected objects a little bit further so you can better differentiate between moving the whole object and moving only a node

### Configuration
Android App 0.7.0

**Comment by dg0yt** [comment]
There is a setting which mitigates the issue: "Editor" > "Click tolerance". If you increase that value, the area which will select the individual node instead of the object frame will be larger.
- Of course this affects other interactions, too.
- Please verify that the dimension is correctly used even on high-dpi screens.
- Once we start handling touch different from mouse input, we may use a different value for touch input.

I admit that there is no visual clue for touch input. For mouse input, there are hover effects.

**Comment by Zerbembasqwibo** [comment]
But the same should be used for mouse interaction, why not?

**Comment by ollesmaps** [comment]
Thank you for the advice @dg0yt. I settled on click tolerance 5mm and it works fine now. Thank you. Just for the record my original click tolerance was 3mm. I tried also higher values (7mm), however that was too much as it was making me select objects involuntarily.

**Comment by ollesmaps** [comment]
@dg0yt The only downside of the higher click tolerace I notice is when adding/ deleting nodes. It is less sensible now.

**Comment by ollesmaps** [comment]
This causes troubles also reversely. If you want to just move object, you can move node instead. I think the click tolerance adjustment works for move object / move node in opposite ways. So another solution shall be applied.
